# Dane o kodach flag wykorzystywanych przez ACO
countries_ACO = {
"119": "ITA", "70": "FRA", "219": "CHE", "184": "PRT", "181": "POL", "188": "GBR", "5": "DEU", "240": "TUR", "23": "BEL", "138": "LUX",
"170": "OMN", "92": "HKG", "121": "JPN", "66": "USA", "213": "SVK", "64": "ESP", "40": "CAN", "254": "RAF", "178": "NLD", "57": "DNK",
"43": "CHN", "189": "RUS", "17": "AUT", "179": "PHI", "227": "TWN", "212": "SGP", "253": "TPE", "142": "MYS", "": ""
}

# Dane o kierowcach
drivers = {
"aaron telitz": {"country": "USA", "link": "[[Aaron Telitz]]"},
"adam ali": {"country": "CAN", "link": "[[Adam Ali]]"},
"adrien chila": {"country": "FRA", "link": "[[Adrien Chila]]"},
"ahmad al harthy": {"country": "OMN", "link": "[[Ahmad al-Harisi|Ahmad Al Harthy]]"},
"alan brynjolfsson": {"country": "USA", "link": "[[Alan Brynjolfsson]]"},
"alan metni": {"country": "USA", "link": "[[Alan Metni]]"},
"albert costa": {"country": "ESP", "link": "[[Albert Costa (kierowca wyścigowy)|Albert Costa]]"},
"alec udell": {"country": "USA", "link": "[[Alec Udell]]"},
"alejandro garcia": {"country": "MEX", "link": "[[Alejandro García González|Alejandro García]]"},
"alessandro pier guidi": {"country": "ITA", "link": "[[Alessandro Pier Guidi]]"},
"alessio picariello": {"country": "BEL", "link": "[[Alessio Picariello]]"},
"alessio rovera": {"country": "ITA", "link": "[[Alessio Rovera]]"},
"alex kirby": {"country": "USA", "link": "[[Alex Kirby]]"},
"alex lynn": {"country": "GBR", "link": "[[Alex Lynn]]"},
"alex quinn": {"country": "GBR", "link": "[[Alex Quinn]]"},
"alex riberas": {"country": "ESP", "link": "[[Alex Riberas]]"},
"alexander bukhantsov": {"country": "ARE", "link": "[[Alexander Bukhantsov]]"},
"alexander lynn": {"country": "GBR", "link": "[[Alex Lynn|Alexander Lynn]]"},
"alexander mattschull": {"country": "DEU", "link": "[[Alexander Mattschull]]"},
"alexander sims": {"country": "GBR", "link": "[[Alexander Sims]]"},
"alexandre coigny": {"country": "CHE", "link": "[[Alexandre Coigny]]"},
"anders fjordbach": {"country": "DNK", "link": "[[Anders Fjordbach]]"},
"andrea caldarelli": {"country": "ITA", "link": "[[Andrea Caldarelli]]"},
"andreas laskaratos": {"country": "GRC", "link": "[[Andreas Laskaratos]]"},
"andrew haryanto": {"country": "IDN", "link": "[[Andrew Haryanto]]"},
"andrew meyrick": {"country": "GBR", "link": "[[Andy Meyrick|Andrew Meyrick]]"},
"andrew pinkerton": {"country": "USA", "link": "[[Andrew Pinkerton]]"},
"andré lotterer": {"country": "DEU", "link": "[[André Lotterer]]"},
"andré negrão": {"country": "BRA", "link": "[[André Negrão]]"},
"andy lally": {"country": "USA", "link": "[[Andy Lally]]"},
"anthony mantella": {"country": "CAN", "link": "[[Anthony Mantella]]"},
"anthony wells": {"country": "GBR", "link": "[[Anthony Wells]]"},
"antoine doquin": {"country": "FRA", "link": "[[Antoine Doquin]]"},
"antonio felix da costa": {"country": "PRT", "link": "[[António Félix da Costa]]"},
"antonio fuoco": {"country": "ITA", "link": "[[Antonio Fuoco]]"},
"antonio garcia": {"country": "ESP", "link": "[[Antonio García (kierowca)|Antonio García]]"},
"antonio giovinazzi": {"country": "ITA", "link": "[[Antonio Giovinazzi]]"},
"ari balogh": {"country": "USA", "link": "[[Ari Balogh]]"},
"arnold robin": {"country": "FRA", "link": "[[Arnold Robin]]"},
"ashton harrison": {"country": "USA", "link": "[[Ashton Harrison]]"},
"augusto farfus": {"country": "BRA", "link": "[[Augusto Farfus]]"},
"axcil jefferies": {"country": "GBR", "link": "[[Axcil Jefferies]]"},
"ben barnicoat": {"country": "GBR", "link": "[[Ben Barnicoat]]"},
"ben hanley": {"country": "GBR", "link": "[[Ben Hanley]]"},
"ben keating": {"country": "USA", "link": "[[Ben Keating]]"},
"ben tuck": {"country": "GBR", "link": "[[Ben Tuck]]"},
"benjamin barker": {"country": "GBR", "link": "[[Ben Barker (kierowca wyścigowy)|Benjamin Barker]]"},
"bent viscaal": {"country": "NLD", "link": "[[Bent Viscaal]]"},
"bill auberlen": {"country": "USA", "link": "[[Bill Auberlen]]"},
"brendan iribe": {"country": "USA", "link": "[[Brendan Iribe]]"},
"brendon hartley": {"country": "NZL", "link": "[[Brendon Hartley]]"},
"bryan sellers": {"country": "USA", "link": "[[Bryan Sellers]]"},
"casper stevenson": {"country": "GBR", "link": "[[Casper Stevenson]]"},
"chandler hull": {"country": "USA", "link": "[[Chandler Hull]]"},
"charles milesi": {"country": "FRA", "link": "[[Charles Milesi]]"},
"charles scardina": {"country": "USA", "link": "[[Charles Scardina]]"},
"charlie eastwood": {"country": "IRL", "link": "[[Charlie Eastwood]]"},
"christian rasmussen": {"country": "DNK", "link": "[[Christian Rasmussen]]"},
"christian ried": {"country": "DEU", "link": "[[Christian Ried]]"},
"christopher allen": {"country": "USA", "link": "[[Christopher Allen]]"},
"claudio schiavoni": {"country": "ITA", "link": "[[Claudio Schiavoni]]"},
"colin braun": {"country": "USA", "link": "[[Colin Braun]]"},
"connor bloum": {"country": "USA", "link": "[[Connor Bloum]]"},
"connor de phillippi": {"country": "USA", "link": "[[Connor De Phillippi]]"},
"conrad laursen": {"country": "DNK", "link": "[[Conrad Laursen]]"},
"corey lewis": {"country": "USA", "link": "[[Corey Lewis]]"},
"dakota dickerson": {"country": "USA", "link": "[[Dakota Dickerson]]"},
"dan goldburg": {"country": "USA", "link": "[[Dan Goldburg]]"},
"dane cameron": {"country": "USA", "link": "[[Dane Cameron]]"},
"daniel juncadella": {"country": "ESP", "link": "[[Daniel Juncadella]]"},
"daniel mancinelli": {"country": "ITA", "link": "[[Daniel Mancinelli]]"},
"daniel schneider": {"country": "BRA", "link": "[[Daniel Schneider]]"},
"daniel serra": {"country": "BRA", "link": "[[Daniel Serra]]"},
"daniil kvyat": {"country": "", "link": "[[Daniił Kwiat]]"},
"danny formal": {"country": "CRI", "link": "[[Danny Formal]]"},
"david beckmann": {"country": "DEU", "link": "[[David Beckmann]]"},
"david brule": {"country": "USA", "link": "[[David Brule]]"},
"david heinemeier-hansson": {"country": "DNK", "link": "[[David Heinemeier Hansson|David Heinemeier-Hansson]]"},
"david perel": {"country": "ZAF", "link": "[[David Perel]]"},
"david pittard": {"country": "GBR", "link": "[[David Pittard]]"},
"davide rigon": {"country": "ITA", "link": "[[Davide Rigon]]"},
"dennis andersem": {"country": "DNK", "link": "[[Dennis Andersen]]"},
"dennis andersen": {"country": "DNK", "link": "[[Dennis Andersen]]"},
"devlin defrancesco": {"country": "CAN", "link": "[[Devlin DeFrancesco]]"},
"diego alessi": {"country": "ITA", "link": "[[Diego Alessi]]"},
"donald yount": {"country": "USA", "link": "[[Donald Yount]]"},
"doriane pin": {"country": "FRA", "link": "[[Doriane Pin]]"},
"dries vanthoor": {"country": "BEL", "link": "[[Dries Vanthoor]]"},
"duncan cameron": {"country": "GBR", "link": "[[Duncan Cameron]]"},
"dwight merriman": {"country": "USA", "link": "[[Dwight Merriman]]"},
"earl bamber": {"country": "NZL", "link": "[[Earl Bamber]]"},
"ed jones": {"country": "ARE", "link": "[[Ed Jones (kierowca)|Ed Jones]]"},
"efrin castro": {"country": "DOM", "link": "[[Efrin Castro]]"},
"eric lux": {"country": "USA", "link": "[[Eric Lux (kierowca wyścigowy)|Eric Lux]]"},
"eric trouillet": {"country": "FRA", "link": "[[Eric Trouillet]]"},
"esteban guerrieri": {"country": "ARG", "link": "[[Esteban Guerrieri]]"},
"esteban gutierrez": {"country": "MEX", "link": "[[Esteban Gutiérrez]]"},
"fabien michal": {"country": "FRA", "link": "[[Fabien Michal]]"},
"fabio scherer": {"country": "CHE", "link": "[[Fabio Scherer]]"},
"felipe fraga": {"country": "BRA", "link": "[[Felipe Fraga]]"},
"felipe nasr": {"country": "BRA", "link": "[[Felipe Nasr]]"},
"ferdinand habsburg": {"country": "AUT", "link": "[[Ferdinand Zvonimir Habsburg-Lothringen|Ferdinand Habsburg]]"},
"filip ugran": {"country": "ROU", "link": "[[Filip Ugran]]"},
"filipe albuquerque": {"country": "PRT", "link": "[[Filipe Albuquerque]]"},
"francesco castellacci": {"country": "ITA", "link": "[[Francesco Castellacci]]"},
"franck mailleux": {"country": "FRA", "link": "[[Franck Mailleux]]"},
"franck perera": {"country": "FRA", "link": "[[Franck Perera]]"},
"frankie montecalvo": {"country": "USA", "link": "[[Frankie Montecalvo]]"},
"francois perrodo": {"country": "FRA", "link": "[[François Perrodo]]"},
"françois heriau": {"country": "FRA", "link": "[[François Heriau]]"},
"françois perrodo": {"country": "FRA", "link": "[[François Perrodo]]"},
"fred poordad": {"country": "USA", "link": "[[Fred Poordad]]"},
"frederick lubin": {"country": "GBR", "link": "[[Frederick Lubin]]"},
"frederik schandorff": {"country": "DNK", "link": "[[Frederik Schandorff]]"},
"frédéric makowiecki": {"country": "FRA", "link": "[[Frédéric Makowiecki]]"},
"gabby chaves": {"country": "COL", "link": "[[Gabriel Chaves|Gabby Chaves]]"},
"gabriel aubry": {"country": "FRA", "link": "[[Gabriel Aubry (kierowca wyścigowy)|Gabriel Aubry]]"},
"gael julien": {"country": "FRA", "link": "[[Gael Julien]]"},
"gar robinson": {"country": "USA", "link": "[[Gar Robinson]]"},
"garett grist": {"country": "CAN", "link": "[[Garett Grist]]"},
"garnet patterson": {"country": "AUS", "link": "[[Garnet Patterson]]"},
"george kurtz": {"country": "USA", "link": "[[George Kurtz]]"},
"giacomo petrobelli": {"country": "ITA", "link": "[[Giacomo Petrobelli]]"},
"giammarco levorato": {"country": "ITA", "link": "[[Giammarco Levorato]]"},
"gianmaria bruni": {"country": "ITA", "link": "[[Gianmaria Bruni]]"},
"giedo van der garde": {"country": "NLD", "link": "[[Giedo van der Garde]]"},
"giorgio roda": {"country": "ITA", "link": "[[Giorgio Roda]]"},
"giorgio sernagiotto": {"country": "ITA", "link": "[[Giorgio Sernagiotto]]"},
"glenn van berlo": {"country": "NLD", "link": "[[Glenn van Berlo]]"},
"gregory huffaker ii": {"country": "USA", "link": "[[Scott Huffaker|Gregory Huffaker II]]"},
"guilherme moura de oliveira": {"country": "PRT", "link": "[[Guilherme de Oliveira]]"},
"gunnar jeannette": {"country": "USA", "link": "[[Gunnar Jeannette]]"},
"gustav birch": {"country": "DNK", "link": "[[Gustav Birch]]"},
"gustav dahlmann birch": {"country": "DNK", "link": "[[Gustav Birch]]"},
"gustavo menezes": {"country": "USA", "link": "[[Gustavo Menezes]]"},
"guy smith": {"country": "GBR", "link": "[[Guy Smith (kierowca)|Guy Smith]]"},
"harry tincknell": {"country": "GBR", "link": "[[Harry Tincknell]]"},
"helio castronoves": {"country": "BRA", "link": "[[Hélio Castroneves]]"},
"henrik hedman": {"country": "SWE", "link": "[[Henrik Hedman]]"},
"horst felbermayr": {"country": "AUT", "link": "[[Horst Felbermayr]]"},
"ian james": {"country": "USA", "link": "[[Ian James]]"},
"ian rodriguez": {"country": "GTM", "link": "[[Ian Rodríguez]]"},
"indy dontje": {"country": "NLD", "link": "[[Indy Dontje]]"},
"jack aitken": {"country": "GBR", "link": "[[Jack Aitken]]"},
"jack hawksworth": {"country": "GBR", "link": "[[Jack Hawksworth]]"},
"jack manchester": {"country": "GBR", "link": "[[Jack Manchester]]"},
"jacques villeneuve": {"country": "CAN", "link": "[[Jacques Villeneuve]]"},
"jacques wolff": {"country": "FRA", "link": "[[Jacques Wolff]]"},
"jaden conwright": {"country": "USA", "link": "[[Jaden Conwright]]"},
"jakub smiechowski": {"country": "POL", "link": "[[Jakub Śmiechowski]]"},
"james allen": {"country": "AUS", "link": "[[James Allen (kierowca wyścigowy)|James Allen]]"},
"james calado": {"country": "GBR", "link": "[[James Calado]]"},
"james dayson": {"country": "CAN", "link": "[[James Dayson]]"},
"james mcguire": {"country": "USA", "link": "[[James McGuire]]"},
"james winslow": {"country": "GBR", "link": "[[James Winslow]]"},
"jan heylen": {"country": "BEL", "link": "[[Jan Heylen]]"},
"jan magnussen": {"country": "DNK", "link": "[[Jan Magnussen]]"},
"jarett andretti": {"country": "USA", "link": "[[Jarett Andretti]]"},
"jason rabe": {"country": "USA", "link": "[[Jason Rabe]]"},
"jaxon evans": {"country": "NZL", "link": "[[Jaxon Evans]]"},
"jean-baptiste lahaye": {"country": "FRA", "link": "[[Jean-Baptiste Lahaye]]"},
"jean-ludovic foubert": {"country": "FRA", "link": "[[Jean-Ludovic Foubert]]"},
"jean-éric vergne": {"country": "FRA", "link": "[[Jean-Éric Vergne]]"},
"jeffrey segal": {"country": "USA", "link": "[[Jeffrey Segal]]"},
"jens møller": {"country": "DNK", "link": "[[Jens Reno Møller]]"},
"jens reno møller": {"country": "DNK", "link": "[[Jens Reno Møller]]"},
"jenson button": {"country": "GBR", "link": "[[Jenson Button]]"},
"jimmie johnson": {"country": "USA", "link": "[[Jimmie Johnson]]"},
"joao barbosa": {"country": "USA", "link": "[[João Barbosa]]"},
"joao paulo de oliveira": {"country": "BRA", "link": "[[João Paulo de Oliveira (kierowca)|João Paulo de Oliveira]]"},
"job van uitert": {"country": "NLD", "link": "[[Job van Uitert]]"},
"john edwards": {"country": "USA", "link": "[[John Michael Edwards|John Edwards]]"},
"john falb": {"country": "USA", "link": "[[John Falb]]"},
"john hartshorne": {"country": "GBR", "link": "[[John Hartshorne]]"},
"john potter": {"country": "USA", "link": "[[John Potter]]"},
"johnny laursen": {"country": "DNK", "link": "[[Johnny Laursen]]"},
"jon lancaster": {"country": "GBR", "link": "[[Jon Lancaster]]"},
"jonas ried": {"country": "DEU", "link": "[[Jonas Ried]]"},
"jonathan aberdein": {"country": "ZAF", "link": "[[Jonathan Aberdein]]"},
"jonathan adam": {"country": "GBR", "link": "[[Jonathan Adam]]"},
"jordan pepper": {"country": "ZAF", "link": "[[Jordan Pepper]]"},
"jordan taylor": {"country": "USA", "link": "[[Jordan Taylor]]"},
"jose maria lopez": {"country": "ARG", "link": "[[José María López]]"},
"josef newgarden": {"country": "USA", "link": "[[Josef Newgarden]]"},
"josh burdon": {"country": "AUS", "link": "[[Josh Burdon]]"},
"josh pierson": {"country": "USA", "link": "[[Joshua Pierson|Josh Pierson]]"},
"joshua pierson": {"country": "USA", "link": "[[Joshua Pierson|Josh Pierson]]"},
"juan manuel correa": {"country": "USA", "link": "[[Juan Manuel Correa]]"},
"juan pablo montoya": {"country": "COL", "link": "[[Juan Pablo Montoya]]"},
"jules gounon": {"country": "FRA", "link": "[[Jules Gounon]]"},
"julien andlauer": {"country": "FRA", "link": "[[Julien Andlauer]]"},
"julien canal": {"country": "FRA", "link": "[[Julien Canal]]"},
"julien piguet": {"country": "FRA", "link": "[[Julien Piguet]]"},
"kai askey": {"country": "GBR", "link": "[[Kai Askey]]"},
"kamui kobayashi": {"country": "JPN", "link": "[[Kamui Kobayashi]]"},
"katherine legge": {"country": "GBR", "link": "[[Katherine Legge]]"},
"kay van berlo": {"country": "NLD", "link": "[[Kay van Berlo]]"},
"kei cozzolino": {"country": "JPN", "link": "[[Kei Cozzolino]]"},
"kenton koch": {"country": "USA", "link": "[[Kenton Koch]]"},
"klaus bachler": {"country": "AUT", "link": "[[Klaus Bachler]]"},
"kriton lentoudis": {"country": "GRC", "link": "[[Kriton Lentoudis]]"},
"kyffin simpson": {"country": "BRB", "link": "[[Kyffin Simpson]]"},
"kyle kirkwood": {"country": "USA", "link": "[[Kyle Kirkwood]]"},
"kyle marcelli": {"country": "CAN", "link": "[[Kyle Marcelli]]"},
"kevin estre": {"country": "FRA", "link": "[[Kévin Estre]]"},
"kévin estre": {"country": "FRA", "link": "[[Kévin Estre]]"},
"lance willsey": {"country": "USA", "link": "[[Lance Willsey]]"},
"lars kern": {"country": "DEU", "link": "[[Lars Kern]]"},
"laurens vanthoor": {"country": "BEL", "link": "[[Laurens Vanthoor]]"},
"laurents hörr": {"country": "DEU", "link": "[[Laurents Hörr]]"},
"leonard weiss": {"country": "DEU", "link": "[[Leonard Weiss]]"},
"lilou wadoux ducellier": {"country": "FRA", "link": "[[Lilou Wadoux|Lilou Wadoux Ducellier]]"},
"lilou wadoux": {"country": "FRA", "link": "[[Lilou Wadoux]]"},
"lorcan hanafin": {"country": "GBR", "link": "[[Lorcan Hanafin]]"},
"loris spinelli": {"country": "ITA", "link": "[[Loris Spinelli]]"},
"louis deletraz": {"country": "CHE", "link": "[[Louis Delétraz]]"},
"louis delétraz": {"country": "CHE", "link": "[[Louis Delétraz]]"},
"louis prette": {"country": "ITA", "link": "[[Louis Prette]]"},
"loïc duval": {"country": "FRA", "link": "[[Loïc Duval]]"},
"luis felipe derani": {"country": "BRA", "link": "[[Pipo Derani|Luis Felipe Derani]]"},
"luis perez companc": {"country": "ARG", "link": "[[Luís Pérez Companc]]"},
"luke berkeley": {"country": "USA", "link": "[[Luke Berkeley]]"},
"madison snow": {"country": "USA", "link": "[[Madison Snow]]"},
"malthe jakobsen": {"country": "DNK", "link": "[[Malthe Jakobsen]]"},
"manuel espirito santo": {"country": "PRT", "link": "[[Manuel Espirito Santo]]"},
"manuel maldonado": {"country": "GBR", "link": "[[Manuel Maldonado]]"},
"marc miller": {"country": "USA", "link": "[[Marc Miller]]"},
"marco sorensen": {"country": "DNK", "link": "[[Marco Sørensen]]"},
"marco sørensen": {"country": "DNK", "link": "[[Marco Sørensen]]"},
"marco wittmann": {"country": "DEU", "link": "[[Marco Wittmann]]"},
"marcos siebert": {"country": "ARG", "link": "[[Marcos Siebert]]"},
"maro engel": {"country": "DEU", "link": "[[Maro Engel]]"},
"marino sato": {"country": "JPN", "link": "[[Marino Satō]]"},
"mark kvamme": {"country": "USA", "link": "[[Mark Kvamme]]"},
"martin berry": {"country": "SGP", "link": "[[Martin Berry]]"},
"martin rump": {"country": "EST", "link": "[[Martin Rump]]"},
"mateusz kaprzyk": {"country": "POL", "link": "[[Mateusz Kaprzyk]]"},
"mathias beche": {"country": "CHE", "link": "[[Mathias Beche]]"},
"mathieu jaminet": {"country": "FRA", "link": "[[Mathieu Jaminet]]"},
"matt campbell": {"country": "AUS", "link": "[[Matt Campbell]]"},
"matteo cairoli": {"country": "ITA", "link": "[[Matteo Cairoli]]"},
"matteo cressoni": {"country": "ITA", "link": "[[Matteo Cressoni]]"},
"matthew bell": {"country": "GBR", "link": "Matthew Bell"},
"matthew griffin": {"country": "IRL", "link": "[[Matt Griffin|Matthew Griffin]]"},
"matthew richard bell": {"country": "GBR", "link": "Matthew Richard Bell"},
"matthias kaiser": {"country": "LIE", "link": "[[Matthias Kaiser]]"},
"matthias luethen": {"country": "DEU", "link": "[[Matthias Lüthen]]"},
"matthieu lahaye": {"country": "FRA", "link": "[[Matthieu Lahaye]]"},
"matthieu vaxiviere": {"country": "FRA", "link": "[[Matthieu Vaxivière]]"},
"maxime martin": {"country": "BEL", "link": "[[Maxime Martin]]"},
"maxime robin": {"country": "FRA", "link": "[[Maxime Robin]]"},
"maxwell root": {"country": "USA", "link": "[[Maxwell Root]]"},
"memo rojas": {"country": "MEX", "link": "[[Memo Rojas]]"},
"michael christensen": {"country": "DNK", "link": "[[Michael Christensen]]"},
"michael dinan": {"country": "USA", "link": "[[Michael Dinan]]"},
"michael fassbender": {"country": "IRL", "link": "[[Michael Fassbender]]"},
"michael jensen": {"country": "DNK", "link": "[[Michael Jensen (kierowca wyścigowy)|Michael Jensen]]"},
"michael wainwright": {"country": "GBR", "link": "[[Michael Wainwright]]"},
"michelle gatting": {"country": "DNK", "link": "[[Michelle Gatting]]"},
"miguel cristóvão": {"country": "PRT", "link": "[[Miguel Cristóvão]]"},
"miguel molina": {"country": "ESP", "link": "[[Miguel Molina (kierowca wyścigowy)|Miguel Molina]]"},
"miguel pedro ramos": {"country": "PRT", "link": "[[Miguel Ramos]]"},
"mikael grenier": {"country": "CAN", "link": "[[Mikaël Grenier]]"},
"mike conway": {"country": "GBR", "link": "[[Mike Conway]]"},
"mike rockenfeller": {"country": "DEU", "link": "[[Mike Rockenfeller]]"},
"mike skeen": {"country": "USA", "link": "[[Mike Skeen]]"},
"mikkel jensen": {"country": "DNK", "link": "[[Mikkel Jensen]]"},
"mikkel mac": {"country": "DNK", "link": "[[Mikkel Mac]]"},
"mikkel pedersen": {"country": "DNK", "link": "[[Mikkel Pedersen]]"},
"mirko bortolotti": {"country": "ITA", "link": "[[Mirko Bortolotti]]"},
"misha goikhberg": {"country": "CAN", "link": "[[Misha Goikhberg]]"},
"naoki yokomizo": {"country": "JPN", "link": "[[Naoki Yokomizo]]"},
"nathanael berthon": {"country": "FRA", "link": "[[Nathanaël Berthon]]"},
"nathanaël berthon": {"country": "FRA", "link": "[[Nathanaël Berthon]]"},
"neel jani": {"country": "CHE", "link": "[[Neel Jani]]"},
"nelson piquet jr": {"country": "BRA", "link": "[[Nelson Piquet Jr.]]"},
"nicholas tandy": {"country": "GBR", "link": "[[Nick Tandy]]"},
"nick adcock": {"country": "GBR", "link": "[[Nick Adcock]]"},
"nick moss": {"country": "GBR", "link": "[[Nick Moss]]"},
"nick tandy": {"country": "GBR", "link": "[[Nick Tandy]]"},
"nick yelloly": {"country": "GBR", "link": "[[Nick Yelloly]]"},
"nicki thiim": {"country": "DNK", "link": "[[Nicki Thiim]]"},
"nicklas nielsen": {"country": "DNK", "link": "[[Nicklas Nielsen]]"},
"nicky catsburg": {"country": "NLD", "link": "[[Nick Catsburg|Nicky Catsburg]]"},
"nico müller": {"country": "CHE", "link": "[[Nico Müller]]"},
"nico pino": {"country": "CHL", "link": "[[Nicolás Pino (kierowca wyścigowy)|Nico Pino]]"},
"nico varrone": {"country": "ARG", "link": "[[Nicolás Varrone]]"},
"nicolas lapierre": {"country": "FRA", "link": "[[Nicolas Lapierre]]"},
"nicolas pino": {"country": "GBR", "link": "[[Nicolás Pino (kierowca wyścigowy)|Nicolás Pino]]"},
"nicolas varrone": {"country": "ARG", "link": "[[Nicolás Varrone]]"},
"nolan siegel": {"country": "USA", "link": "[[Nolan Siegel]]"},
"norman nato": {"country": "FRA", "link": "[[Norman Nato]]"},
"oliver jarvis": {"country": "GBR", "link": "[[Oliver Jarvis]]"},
"oliver rasmussen": {"country": "DNK", "link": "[[Oliver Rasmussen]]"},
"olivier pla": {"country": "FRA", "link": "[[Olivier Pla]]"},
"olli caldwell": {"country": "GBR", "link": "[[Olli Caldwell]]"},
"ollie millroy": {"country": "GBR", "link": "[[Ollie Millroy]]"},
"onofrio triarsi": {"country": "USA", "link": "[[Onofrio Triarsi]]"},
"orey fidani": {"country": "CAN", "link": "[[Orey Fidani]]"},
"oscar tunjo": {"country": "COL", "link": "[[Oscar Andrés Tunjo|Oscar Tunjo]]"},
"parker thompson": {"country": "CAN", "link": "[[Parker Thompson]]"},
"patrick gallagher": {"country": "USA", "link": "[[Patrick Gallagher (kierowca wyścigowy)|Patrick Gallagher]]"},
"patrick liddy": {"country": "USA", "link": "[[Patrick Liddy]]"},
"patrick pilet": {"country": "FRA", "link": "[[Patrick Pilet]]"},
"paul dalla lana": {"country": "CAN", "link": "[[Paul Dalla Lana]]"},
"paul di resta": {"country": "GBR", "link": "[[Paul di Resta]]"},
"paul lafargue": {"country": "FRA", "link": "[[Paul Lafargue (kierowca wyścigowy)|Paul Lafargue]]"},
"paul loup chatin": {"country": "FRA", "link": "[[Paul-Loup Chatin]]"},
"paul-loup chatin": {"country": "FRA", "link": "[[Paul-Loup Chatin]]"},
"pedro perino": {"country": "PRT", "link": "[[Pedro Perino]]"},
"philip ellis": {"country": "GBR", "link": "[[Philip Ellis]]"},
"philip hanson": {"country": "GBR", "link": "[[Philip Hanson]]"},
"philipp eng": {"country": "AUT", "link": "[[Philipp Eng]]"},
"pietro fittipaldi": {"country": "BRA", "link": "[[Pietro Fittipaldi]]"},
"pipo derani": {"country": "BRA", "link": "[[Pipo Derani]]"},
"pj hyett": {"country": "USA", "link": "[[P.J. Hyett]]"},
"raffaele marciello": {"country": "CHE", "link": "[[Raffaele Marciello]]"},
"rahel frey": {"country": "CHE", "link": "[[Rahel Frey]]"},
"rasmus lindh": {"country": "SWE", "link": "[[Rasmus Lindh]]"},
"renger van der zande": {"country": "NLD", "link": "[[Renger van der Zande]]"},
"rené binder": {"country": "AUT", "link": "[[René Binder]]"},
"rené rast": {"country": "DEU", "link": "[[René Rast]]"},
"reshad de gerus": {"country": "FRA", "link": "[[Reshad de Gerus]]"},
"reshad de gérus": {"country": "FRA", "link": "[[Reshad de Gerus]]"},
"riccardo pera": {"country": "ITA", "link": "[[Riccardo Pera]]"},
"richard lietz": {"country": "AUT", "link": "[[Richard Lietz]]"},
"richard westbrook": {"country": "GBR", "link": "[[Richard Westbrook]]"},
"ricky taylor": {"country": "USA", "link": "[[Ricky Taylor]]"},
"rob ferriol": {"country": "USA", "link": "[[Rob Ferriol]]"},
"robby foley": {"country": "USA", "link": "[[Robby Foley]]"},
"robert kubica": {"country": "POL", "link": "[[Robert Kubica]]"},
"roberto lacorte": {"country": "ITA", "link": "[[Roberto Lacorte]]"},
"robin frijns": {"country": "NLD", "link": "[[Robin Frijns]]"},
"rodrigo sales": {"country": "USA", "link": "[[Rodrigo Sales]]"},
"romain dumas": {"country": "FRA", "link": "[[Romain Dumas]]"},
"roman de angelis": {"country": "CAN", "link": "[[Roman De Angelis]]"},
"ross gunn": {"country": "GBR", "link": "[[Ross Gunn]]"},
"rui aguas": {"country": "PRT", "link": "[[Rui Águas (kierowca wyścigowy)|Rui Águas]]"},
"rui andrade": {"country": "AGO", "link": "[[Rui Pinto de Andrade|Rui Andrade]]"},
"russell ward": {"country": "USA", "link": "[[Russell Ward]]"},
"ryan briscoe": {"country": "AUS", "link": "[[Ryan Briscoe]]"},
"ryan cullen": {"country": "GBR", "link": "[[Ryan Cullen]]"},
"ryan dalziel": {"country": "GBR", "link": "[[Ryan Dalziel]]"},
"ryan hardwick": {"country": "USA", "link": "[[Ryan Hardwick]]"},
"ryan harper-ellam": {"country": "GBR", "link": "[[Ryan Harper-Ellam]]"},
"ryo hirakawa": {"country": "JPN", "link": "[[Ryō Hirakawa]]"},
"salih yoluc": {"country": "TUR", "link": "[[Salih Yoluç]]"},
"sarah bovy": {"country": "BEL", "link": "[[Sarah Bovy]]"},
"satoshi hoshino": {"country": "JPN", "link": "[[Satoshi Hoshino]]"},
"scott dixon": {"country": "NZL", "link": "[[Scott Dixon]]"},
"scott huffaker": {"country": "USA", "link": "[[Scott Huffaker]]"},
"scott mclaughlin": {"country": "NZL", "link": "[[Scott McLaughlin]]"},
"sean gelael": {"country": "IDN", "link": "[[Sean Gelael]]"},
"seb priaulx": {"country": "GBR", "link": "[[Sebastian Priaulx|Seb Priaulx]]"},
"sebastian alvarez": {"country": "GBR", "link": "[[Sebastián Álvarez]]"},
"sebastian montoya": {"country": "COL", "link": "[[Sebastián Montoya]]"},
"sebastien bourdais": {"country": "FRA", "link": "[[Sébastien Bourdais]]"},
"seth lucas": {"country": "USA", "link": "[[Seth Lucas]]"},
"sheena monk": {"country": "USA", "link": "[[Sheena Monk]]"},
"sheldon van der linde" : {"country": "ZAF", "link": "[[Sheldon van der Linde]]"},
"simon mann": {"country": "USA", "link": "[[Simon Mann (kierowca wyścigowy)|Simon Mann]]"},
"simon pagenaud": {"country": "FRA", "link": "[[Simon Pagenaud]]"},
"spencer pumpelly": {"country": "USA", "link": "[[Spencer Pumpelly]]"},
"stevan mcaleer": {"country": "GBR", "link": "[[Stevan McAleer]]"},
"steven thomas": {"country": "USA", "link": "[[Steven Thomas]]"},
"sébastien bourdais": {"country": "FRA", "link": "[[Sébastien Bourdais]]"},
"sébastien buemi": {"country": "CHE", "link": "[[Sébastien Buemi]]"},
"takeshi kimura": {"country": "JPN", "link": "[[Takeshi Kimura]]"},
"tatiana calderon": {"country": "COL", "link": "[[Tatiana Calderón]]"},
"thomas flohr": {"country": "CHE", "link": "[[Thomas Flohr]]"},
"thomas merrill": {"country": "USA", "link" : "[[Thomas Merrill]]"},
"thomas neubauer": {"country": "FRA", "link": "[[Thomas Neubauer]]"},
"tijmen van der helm": {"country": "NLD", "link": "[[Tijmen van der Helm]]"},
"till bechtolsheimer": {"country": "GBR", "link": "[[Till Bechtolsheimer]]"},
"tom blomqvist": {"country": "GBR", "link": "[[Tom Blomqvist]]"},
"tom dillmann": {"country": "FRA", "link": "[[Tom Dillmann]]"},
"tom gamble": {"country": "GBR", "link": "[[Tom Gamble]]"},
"tom van rompuy": {"country": "BEL", "link": "[[Tom van Rompuy]]"},
"tomonobu fujii": {"country": "JPN", "link": "[[Tomonobu Fujii]]"},
"tommy milner": {"country": "USA", "link": "[[Tommy Milner]]"},
"tonis kasemets": {"country": "USA", "link": "[[Tonis Kasemets]]"},
"torsten kratz": {"country": "DEU", "link": "[[Torsten Kratz]]"},
"trent hindman": {"country": "USA", "link": "[[Trent Hindman]]"},
"trenton estep": {"country": "USA", "link": "[[Trenton Estep]]"},
"tristan vautier": {"country": "FRA", "link": "[[Tristan Vautier]]"},
"ugo de wilde": {"country": "BEL", "link": "[[Ugo de Wilde]]"},
"ulysse de pauw": {"country": "BEL", "link": "[[Ulysse de Pauw]]"},
"valdemar eriksen": {"country": "DNK", "link": "[[Valdemar Eriksen]]"},
"valentin hasse-clot": {"country": "FRA", "link": "[[Valentin Hasse-Clot]]"},
"vladislav lomko": {"country": "", "link": "[[Władisław Łomko]]"},
"wayne boyd": {"country": "GBR", "link": "[[Wayne Boyd]]"},
"will stevens": {"country": "GBR", "link": "[[Will Stevens]]"},
"william stevens": {"country": "GBR", "link": "[[Will Stevens|William Stevens]]"},
"wyatt brichacek": {"country": "USA", "link": "[[Wyatt Brichacek]]"},
"yifei ye": {"country": "CHN", "link": "[[Ye Yifei|Yifei Ye]]"},
"yorikatsu tsujiko": {"country": "JPN", "link": "[[Yorikatsu Tsujiko]]"},
"zacharie robichon": {"country": "CAN", "link": "[[Zacharie Robichon]]"},
}

# Dane o zespołach
teams = {
"#01 Cadillac Racing": {"country": "USA", "link": "#01 [[Chip Ganassi Racing|Cadillac Racing]]"},
"#023 Triarsi Competizione": {"country": "USA", "link": "#023 [[Triarsi Competizione]]"},
"#04 Crowdstrike Racing by APR": {"country": "USA", "link": "#04 Crowdstrike Racing by [[Algarve Pro Racing|APR]]"},
"#1 Paul Miller Racing": {"country": "USA", "link": "#1 [[Paul Miller Racing]]"},
"#10 Eurointernational": {"country": "ITA", "link": "#10 [[EuroInternational|Eurointernational]]"},
"#10 Konica Minolta Acura ARX-06": {"country": "USA", "link": "#10 [[Wayne Taylor Racing|Konica Minolta Acura ARX-06]]"},
"#10 Vector Sport": {"country": "GBR", "link": "#10 [[Vector Sport]]"},
"#100 Walkenhorst Motorsport": {"country": "DEU", "link": "#100 [[Walkenhorst Motorsport]]"},
"#11 Eurointernational": {"country": "ITA", "link": "#11 [[EuroInternational|Eurointernational]]"},
"#11 TDS Racing": {"country": "FRA", "link": "#11 [[TDS Racing]]"},
"#12 Vasser Sullivan": {"country": "USA", "link": "#12 [[SH Racing|Vasser Sullivan]]"},
"#12 WTM Racing by Rinaldi": {"country": "DEU", "link": "#12 WTM by [[Rinaldi Racing]]"},
"#12 WTM by Rinaldi Racing": {"country": "DEU", "link": "#12 WTM by [[Rinaldi Racing]]"},
"#13 AWA": {"country": "CAN", "link": "#13 [[AWA]]"},
"#13 Inter Europol Competition": {"country": "POL", "link": "#13 [[Inter Europol Competition]]"},
"#13 Tower Motorsports": {"country": "CAN", "link": "#13 [[Tower Motorsports]]"},
"#14 Nielsen Racing": {"country": "GBR", "link": "#14 [[Nielsen Racing]]"},
"#14 Vasser Sullivan": {"country": "USA", "link": "#14 [[SH Racing|Vasser Sullivan]]"},
"#15 RLR MSport": {"country": "GBR", "link": "#15 [[RLR MSport]]"},
"#15 RLR M Sport": {"country": "GBR", "link": "#15 [[RLR MSport]]"},
"#16 Proton Competition": {"country": "DEU", "link": "#16 [[Proton Competition]]"},
"#16 Wright Motorsports": {"country": "USA", "link": "#16 [[Wright Motorsports]]"},
"#17 AWA": {"country": "CAN", "link": "#17 [[AWA]]"},
"#17 COOL Racing": {"country": "CHE", "link": "#17 [[Cool Racing|COOL Racing]]"},
"#18 Era Motorsport": {"country": "USA", "link": "#18 [[Era Motorsport]]"},
"#19 Team Virage": {"country": "POL", "link": "#19 [[Team Virage]]"},
"#2 Cadillac Racing": {"country": "USA", "link": "#2 [[Chip Ganassi Racing|Cadillac Racing]]"},
"#20 Algarve Pro Racing": {"country": "PRT", "link": "#20 [[Algarve Pro Racing]]"},
"#20 High Class Racing": {"country": "DNK", "link": "#20 [[High Class Racing]]"},
"#21 AF Corse": {"country": "ITA", "link": "#21 [[AF Corse]]"},
"#21 United Autosports USA": {"country": "USA", "link": "#21 [[United Autosports|United Autosports USA]]"},
"#22 United Autosports USA": {"country": "USA", "link": "#22 [[United Autosports|United Autosports USA]]"},
"#22 United Autosports": {"country": "GBR", "link": "#22 [[United Autosports]]"},
"#23 Heart of Racing Team": {"country": "USA", "link": "#23 [[Heart of Racing|Heart of Racing Team]]"},
"#23 United Autosports USA": {"country": "USA", "link": "#23 [[United Autosports|United Autosports USA]]"},
"#23 United Autosports": {"country": "GBR", "link": "#23 [[United Autosports]]"},
"#24 BMW M Team RLL": {"country": "USA", "link": "#24 [[BMW#BMW M GmbH|BMW M]] [[Rahal Letterman Lanigan Racing|Team RLL]]"},
"#24 Hendrick Motorsports": {"country": "USA", "link": "#24 [[Hendrick Motorsports]]"},
"#24 Nielsen Racing": {"country": "GBR", "link": "#24 [[Nielsen Racing]]"},
"#25 Algarve Pro Racing": {"country": "PRT", "link": "#25 [[Algarve Pro Racing]]"},
"#25 BMW M Team RLL": {"country": "USA", "link": "#25 [[BMW#BMW M GmbH|BMW M]] [[Rahal Letterman Lanigan Racing|Team RLL]]"},
"#25 ORT by TF": {"country": "OMN", "link": "#25 ORT by [[TF Sport|TF]]"},
"#27 Heart of Racing Team": {"country": "USA", "link": "#27 [[Heart of Racing|Heart of Racing Team]]"},
"#28 IDEC Sport": {"country": "FRA", "link": "#28 [[IDEC Sport Racing|IDEC Sport]]"},
"#28 JOTA": {"country": "GBR", "link": "#28 [[Jota Sport|JOTA]]"},
"#3 Cadillac Racing": {"country": "USA", "link": "#3 [[Chip Ganassi Racing|Cadillac Racing]]"},
"#3 Corvette Racing": {"country": "USA", "link": "#3 [[Pratt & Miller|Corvette Racing]]"},
"#3 DKR Engineering": {"country": "LUX", "link": "#3 [[DKR Engineering]]"},
"#30 Duqueine Team": {"country": "FRA", "link": "#30 [[Duqueine Team]]"},
"#30 Jr III Racing": {"country": "USA", "link": "#30 [[Jr III Racing]]"},
"#31 Racing Spirit of Leman": {"country": "CHE", "link": "#31 [[Racing Spirit of Léman]]"},
"#31 Team WRT": {"country": "BEL", "link": "#31 [[W Racing Team|Team WRT]]"},
"#31 Whelen Engineering Cadillac Racing": {"country": "USA", "link": "#31 [[Action Express Racing|Whelen Engineering Cadillac Racing]]"},
"#311 Action Express Racing": {"country": "USA", "link": "#311 [[Action Express Racing]]"},
"#32 Inter Europol Competition": {"country": "POL", "link": "#32 [[Inter Europol Competition]]"},
"#32 Team Korthoff Motorsports": {"country": "USA", "link": "#32 [[Team Korthoff Motorsports]]"},
"#33 Corvette Racing": {"country": "USA", "link": "#33 [[Pratt & Miller|Corvette Racing]]"},
"#33 Sean Creech Motorsport": {"country": "USA", "link": "#33 [[Sean Creech Motorsport]]"},
"#34 Inter Europol Competition": {"country": "POL", "link": "#34 [[Inter Europol Competition]]"},
"#34 Racing Team Turkey": {"country": "TUR", "link": "#34 [[Racing Team Turkey]]"},
"#35 Alpine Elf Team": {"country": "FRA", "link": "#35 [[Signature Team|Alpine Elf Team]]"},
"#35 TDS Racing": {"country": "FRA", "link": "#35 [[TDS Racing]]"},
"#35 Ultimate": {"country": "FRA", "link": "#35 [[Graff Racing|Ultimate]]"},
"#36 Alpine Elf Team": {"country": "FRA", "link": "#36 [[Signature Team|Alpine Elf Team]]"},
"#36 Andretti Autosport": {"country": "USA", "link": "#36 [[Andretti Autosport]]"},
"#37 COOL Racing": {"country": "CHE", "link": "#37 [[Cool Racing|COOL Racing]]"},
"#38 Hertz Team JOTA": {"country": "GBR", "link": "#38 [[The Hertz Corporation|Hertz]] [[Jota Sport|Team JOTA]]"},
"#38 Performance Tech Motorsports": {"country": "USA", "link": "#38 [[Performance Tech Motorsports]]"},
"#39 Graff Racing": {"country": "FRA", "link": "#39 [[Graff Racing]]"},
"#4 Ave Motorsports": {"country": "USA", "link": "#4 [[Ave Motorsports]]"},
"#4 DKR Engineering": {"country": "LUX", "link": "#4 [[DKR Engineering]]"},
"#4 Floyd Vanwall Racing Team": {"country": "AUT", "link": "#4 [[Kodewa|Floyd Vanwall Racing Team]]"},
"#41 Team WRT": {"country": "BEL", "link": "#41 [[W Racing Team|Team WRT]]"},
"#42 NTE Sport LLC": {"country": "USA", "link": "#42 [[NTE Sport]]"},
"#43 DKR Engineering": {"country": "LUX", "link": "#43 [[DKR Engineering]]"},
"#43 Inter Europol Competition": {"country": "POL", "link": "#43 [[Inter Europol Competition]]"},
"#44 GMB Motorsport": {"country": "DNK", "link": "#44 [[GMB Motorsport]]"},
"#44 Magnus Racing": {"country": "USA", "link": "#44 [[Magnus Racing]]"},
"#45 Algarve Pro Racing": {"country": "PRT", "link": "#45 [[Algarve Pro Racing]]"},
"#47 CETILAR RACING": {"country": "ITA", "link": "#47 [[Cetilar Racing|CETILAR RACING]]"},
"#47 COOL Racing": {"country": "CHE", "link": "#47 [[Cool Racing|COOL Racing]]"},
"#48 IDEC Sport": {"country": "FRA", "link": "#48 [[IDEC Sport Racing|IDEC Sport]]"},
"#5 JDC Miller MotorSports": {"country": "USA", "link": "#5 [[JDC MotorSports|JDC Miller Motorsports]]"},
"#5 Porsche Penske Motorsport": {"country": "DEU", "link": "#5 [[Porsche]] [[Penske Racing|Penske Motorsport]]"},
"#5 RLR MSport": {"country": "GBR", "link": "#5 [[RLR MSport]]"},
"#5 RLR M Sport": {"country": "GBR", "link": "#5 [[RLR MSport]]"},
"#50 Ferrari AF Corse": {"country": "ITA", "link": "#50 [[Ferrari]] [[AF Corse]]"},
"#50 Formula Racing": {"country": "DNK", "link": "#50 [[Formula Racing]]"},
"#51 AF Corse": {"country": "ITA", "link": "#51 [[AF Corse]]"},
"#51 Ferrari AF Corse": {"country": "ITA", "link": "#51 [[Ferrari]] [[AF Corse]]"},
"#51 Rick Ware Racing": {"country": "USA", "link": "#51 [[Rick Ware Racing]]"},
"#52 PR1 Mathiasen Motorsports": {"country": "USA", "link": "#52 [[PR1/Mathiasen Motorsports|PR1 Mathiasen Motorsports]]"},
"#54 AF Corse": {"country": "ITA", "link": "#54 [[AF Corse]]"},
"#54 MLT Motorsports": {"country": "USA", "link": "#54 [[MLT Motorsports]]"},
"#55 GMB Motorsport": {"country": "DNK", "link": "#55 [[GMB Motorsport]]"},
"#55 Spirit of Race": {"country": "CHE", "link": "#55 [[Spirit of Race]]"},
"#56 Project 1 - AO": {"country": "DEU", "link": "#56 [[Team Project 1|Project 1]] – AO"},
"#57 Kessel Racing": {"country": "CHE", "link": "#57 [[Kessel Racing]]"},
"#57 Winward Racing": {"country": "USA", "link": "#57 [[HTP Winward Motorsport|Winward Racing]]"},
"#6 Porsche Penske Motorsport": {"country": "DEU", "link": "#6 [[Porsche]] [[Penske Racing|Penske Motorsport]]"},
"#6 Porsche Penske Motorsports": {"country": "USA", "link": "#6 [[Porsche]] [[Penske Racing|Penske Motorsports]]"},
"#60 Iron Lynx": {"country": "ITA", "link": "#60 [[Iron Lynx]]"},
"#60 Meyer Shank Racing w/ Curb Agajanian": {"country": "USA", "link": "#60 [[Meyer Shank Racing]] w/ [[Curb Agajanian]]"},
"#61 Af Corse": {"country": "ITA", "link": "#61 [[AF Corse]]"},
"#62 Risi Competizione": {"country": "USA", "link": "#62 [[Risi Competizione]]"},
"#63 Iron Lynx": {"country": "ITA", "link": "#63 [[Iron Lynx]]"},
"#63 Prema Racing": {"country": "ITA", "link": "#63 [[Prema Powerteam|Prema Racing]]"},
"#65 Panis Racing": {"country": "FRA", "link": "#65 [[Panis Racing]]"},
"#66 Gradient Racing": {"country": "USA", "link": "#66 [[Gradient Racing]]"},
"#66 JMW Motorsport": {"country": "GBR", "link": "#66 [[JMW Motorsport]]"},
"#7 Nielsen Racing": {"country": "GBR", "link": "#7 [[Nielsen Racing]]"},
"#7 Porsche Penske Motorsports": {"country": "USA", "link": "#7 [[Porsche]] [[Penske Racing|Penske Motorsports]]"},
"#7 Toyota Gazoo Racing": {"country": "JPN", "link": "#7 [[Toyota Gazoo Racing Europe|Toyota Gazoo Racing]]"},
"#70 Inception Racing": {"country": "GBR", "link": "#70 [[Inception Racing]]"},
"#708 Glickenhaus Racing": {"country": "USA", "link": "#708 [[SCG|Glickenhaus Racing]]"},
"#709 Glickenhaus Racing": {"country": "USA", "link": "#709 [[SCG|Glickenhaus Racing]]"},
"#72 TF Sport": {"country": "GBR", "link": "#72 [[TF Sport]]"},
"#74 Kessel Racing": {"country": "CHE", "link": "#74 [[Kessel Racing]]"},
"#74 Riley": {"country": "USA", "link": "#74 [[Riley Technologies|Riley]]"},
"#75 Porsche Penske Motorsport": {"country": "DEU", "link": "#75 [[Porsche]] [[Penske Racing|Penske Motorsport]]"},
"#77 Dempsey - Proton Racing": {"country": "DEU", "link": "#77 [[Patrick Dempsey|Dempsey]] – [[Proton Competition|Proton Racing]]"},
"#77 Proton Competition": {"country": "DEU", "link": "#77 [[Proton Competition]]"},
"#77 Wright Motorsports": {"country": "USA", "link": "#77 [[Wright Motorsports]]"},
"#777 D'Station Racing": {"country": "JPN", "link": "#777 [[D'Station Racing]]"},
"#78 Forte Racing Powered by USRT": {"country": "USA", "link": "#78 Forte Racing Powered by [[US RaceTronics|USRT]]"},
"#79 WeatherTech Racing": {"country": "USA", "link": "#79 [[Proton Competition|WeatherTech Racing]]"},
"#8 Team Virage": {"country": "POL", "link": "#8 [[Team Virage]]"},
"#8 Tower Motorsports": {"country": "USA", "link": "#8 [[Tower Motorsports]]"},
"#8 Toyota Gazoo Racing": {"country": "JPN", "link": "#8 [[Toyota Gazoo Racing Europe|Toyota Gazoo Racing]]"},
"#80 AF Corse": {"country": "ITA", "link": "#80 [[AF Corse]]"},
"#80 AO Racing": {"country": "USA", "link": "#80 [[AO Racing]]"},
"#81 DragonSpeed": {"country": "USA", "link": "#81 [[DragonSpeed]]"},
"#81 DragonSpeed USA": {"country": "USA", "link": "#81 [[DragonSpeed|DragonSpeed USA]]"},
"#83 AF Corse": {"country": "ITA", "link": "#83 [[AF Corse]]"},
"#83 Iron Dames": {"country": "ITA", "link": "#83 [[Iron Lynx|Iron Dames]]"},
"#83 Richard Mille AF Corse": {"country": "ITA", "link": "#83 Richard Mille [[AF Corse]]"},
"#85 Iron Dames": {"country": "ITA", "link": "#85 [[Iron Lynx|Iron Dames]]"},
"#85 JDC Miller MotorSports": {"country": "USA", "link": "#85 [[JDC MotorSports|JDC Miller Motorsports]]"},
"#86 GR Racing": {"country": "GBR", "link": "#86 GR Racing"},
"#88 AF Corse": {"country": "ITA", "link": "#88 [[AF Corse]]"},
"#88 Proton Competition": {"country": "DEU", "link": "#88 [[Proton Competition]]"},
"#9 Pfaff Motorsports": {"country": "CAN", "link": "#9 [[Pfaff Motorsports]]"},
"#9 Prema Racing": {"country": "ITA", "link": "#9 [[Prema Powerteam|Prema Racing]]"},
"#91 Kellymoss with Riley": {"country": "USA", "link": "#91 KellyMoss with [[Riley Technologies|Riley]]"},
"#911 Proton Competition": {"country": "DEU", "link": "#911 [[Proton Competition]]"},
"#92 Kellymoss with Riley": {"country": "USA", "link": "#92 KellyMoss with [[Riley Technologies|Riley]]"},
"#923 Racing Team Turkey": {"country": "TUR", "link": "#923 [[Racing Team Turkey]]"},
"#93 Peugeot TotalEnergies": {"country": "FRA", "link": "#93 [[Peugeot Sport|Peugeot TotalEnergies]]"},
"#93 Proton Competition": {"country": "DEU", "link": "#93 [[Proton Competition]]"},
"#93 Racers Edge Motorsports with WTR": {"country": "USA", "link": "#93 Racers Edge Motorsports with [[Wayne Taylor Racing|WTR]]"},
"#94 Peugeot TotalEnergies": {"country": "FRA", "link": "#94 [[Peugeot Sport|Peugeot TotalEnergies]]"},
"#95 TF Sport": {"country": "GBR", "link": "#95 [[TF Sport]]"},
"#95 Turner Motorsport": {"country": "USA", "link": "#95 [[Turner Motorsport]]"},
"#96 Turner Motorsport": {"country": "USA", "link": "#96 [[Turner Motorsport]]"},
"#98 Northwest AMR": {"country": "CAN", "link": "#98 [[Northwest AMR]]"},
"#99 Proton Competition": {"country": "DEU", "link": "#99 [[Proton Competition]]"},
}

# Linki do artykułów o samochodach
cars = {
"Acura ARX-06": "[[Acura ARX-06]]",
"Acura NSX GT3": "[[Acura NSX GT3|Acura NSX GT3 Evo 22]]",
"Aston Martin Vantage AMR": "[[Aston Martin Vantage GTE (2018)|Aston Martin Vantage AMR]]",
"Aston Martin Vantage GT3": "[[Aston Martin Vantage GT3|Aston Martin Vantage GT3]]",
"BMW M Hybrid V8": "[[BMW M Hybrid V8]]",
"BMW M4 GT3": "[[BMW M4 GT3]]",
"Cadillac V-Series.R": "[[Cadillac V-Series.R]]",
"Chevrolet Corvette C8.R GTD": "[[Chevrolet Corvette C8.R|Chevrolet Corvette C8.R GTD]]",
"Chevrolet Corvette C8.R": "[[Chevrolet Corvette C8.R]]",
"Duqueine D08": "[[Duqueine D-08|Duqueine M30 - D08]]",
"Duqueine M30 - D08 - Nissan": "[[Duqueine D-08|Duqueine M30 – D08]]",
"Ferrari 296 GT3": "[[Ferrari 296 GT3]]",
"Ferrari 488 GTE Evo": "[[Ferrari 488 GTE|Ferrari 488 GTE Evo]]",
"Ferrari 499P": "[[Ferrari 499P]]",
"Glickenhaus 007": "[[Glickenhaus 007 LMH]]",
"Lamborghini Huracan GT3 EVO2": "[[Lamborghini Huracán GT3 (2019)|Lamborghini Huracán GT3 Evo 2]]",
"Lexus RC F GT3": "[[Lexus RC F GT3]]",
"Ligier JS P320 - Nissan": "[[Ligier JS P320]]",
"Ligier JS P320": "[[Ligier JS P320]]",
"McLaren 720S GT3 EVO": "[[McLaren 720S GT3|McLaren 720S GT3 EVO]]",
"Mercedes-AMG GT3": "[[Mercedes-AMG GT3|Mercedes-AMG GT3 Evo]]",
"Oreca 07 - Gibson": "[[Oreca 07]]",
"ORECA LMP2 07": "[[Oreca 07]]",
"Peugeot 9X8": "[[Peugeot 9X8]]",
"Porsche 911 GT3 R (992)": "[[Porsche 911 GT3 R (992)]]",
"Porsche 911 RSR - 19": "[[Porsche 911 RSR-19]]",
"Porsche 963": "[[Porsche 963]]",
"Toyota GR010 HYBRID": "[[Toyota GR010 Hybrid]]",
"Vanwall Vandervell 680": "[[Vanwall Vandervell 680]]",
}