# Dane o kodach flag wykorzystywanych przez ACO
countries_ACO = {
"119": "ITA", "70": "FRA", "219": "CHE", "184": "PRT", "181": "POL", "188": "GBR", "5": "DEU", "240": "TUR", "23": "BEL", "138": "LUX",
"170": "OMN", "92": "HKG", "121": "JPN", "66": "USA", "213": "SVK", "64": "ESP", "40": "CAN", "254": "RAF", "178": "NLD", "57": "DNK",
"43": "CHN", "189": "RUS", "17": "AUT", "179": "PHI", "227": "TWN", "212": "SGP", "253": "TPE", "142": "MYS", "": ""
}

# Dane o kierowcach
drivers = {
"adrien chila": {"country": "FRA", "link": "[[Adrien Chila]]"},
"ahmad al harthy": {"country": "OMN", "link": "[[Ahmad al-Harisi|Ahmad Al Harthy]]"},
"albert costa": {"country": "ESP", "link": "[[Albert Costa (kierowca wyścigowy)|Albert Costa]]"},
"alejandro garcia": {"country": "MEX", "link": "[[Alejandro García González|Alejandro García]]"},
"alessandro pier guidi": {"country": "ITA", "link": "[[Alessandro Pier Guidi]]"},
"alessio picariello": {"country": "BEL", "link": "[[Alessio Picariello]]"},
"alessio rovera": {"country": "ITA", "link": "[[Alessio Rovera]]"},
"alex lynn": {"country": "GBR", "link": "[[Alex Lynn]]"},
"alex quinn": {"country": "GBR", "link": "[[Alex Quinn]]"},
"alex riberas": {"country": "ESP", "link": "[[Alex Riberas]]"},
"alexander bukhantsov": {"country": "ARE", "link": "[[Alexander Bukhantsov]]"},
"alexander lynn": {"country": "GBR", "link": "[[Alex Lynn|Alexander Lynn]]"},
"alexander mattschull": {"country": "DEU", "link": "[[Alexander Mattschull]]"},
"alexander sims": {"country": "GBR", "link": "[[Alexander Sims]]"},
"alexandre coigny": {"country": "CHE", "link": "[[Alexandre Coigny]]"},
"aliaksandr malykhin": {"country": "KNA", "link": "[[Alaksandr Małychin]]"},
"andrea caldarelli": {"country": "ITA", "link": "[[Andrea Caldarelli]]"},
"andreas laskaratos": {"country": "GRC", "link": "[[Andreas Laskaratos]]"},
"andrew haryanto": {"country": "IDN", "link": "[[Andrew Haryanto]]"},
"andrew meyrick": {"country": "GBR", "link": "[[Andy Meyrick|Andrew Meyrick]]"},
"andré lotterer": {"country": "DEU", "link": "[[André Lotterer]]"},
"andré negrão": {"country": "BRA", "link": "[[André Negrão]]"},
"anthony wells": {"country": "GBR", "link": "[[Anthony Wells]]"},
"antoine doquin": {"country": "FRA", "link": "[[Antoine Doquin]]"},
"antonio felix da costa": {"country": "PRT", "link": "[[António Félix da Costa]]"},
"antonio fuoco": {"country": "ITA", "link": "[[Antonio Fuoco]]"},
"antonio giovinazzi": {"country": "ITA", "link": "[[Antonio Giovinazzi]]"},
"antonio serravalle": {"country": "CAN", "link": "[[Antonio Serravalle]]"},
"arnold robin": {"country": "FRA", "link": "[[Arnold Robin]]"},
"augusto farfus": {"country": "BRA", "link": "[[Augusto Farfus]]"},
"axcil jefferies": {"country": "GBR", "link": "[[Axcil Jefferies]]"},
"ben barnicoat": {"country": "GBR", "link": "[[Ben Barnicoat]]"},
"ben hanley": {"country": "GBR", "link": "[[Ben Hanley]]"},
"ben keating": {"country": "USA", "link": "[[Ben Keating]]"},
"ben tuck": {"country": "GBR", "link": "[[Ben Tuck]]"},
"benjamin barker": {"country": "GBR", "link": "[[Ben Barker (kierowca wyścigowy)|Benjamin Barker]]"},
"benjamin barker": {"country": "GBR", "link": "[[Benjamin Barker]]"},
"bent viscaal": {"country": "NLD", "link": "[[Bent Viscaal]]"},
"brendan iribe": {"country": "USA", "link": "[[Brendan Iribe]]"},
"brendon hartley": {"country": "NZL", "link": "[[Brendon Hartley]]"},
"callum ilott": {"country": "GBR", "link": "[[Callum Ilott]]"},
"carl wattana bennett": {"country": "THA", "link": "[[Carl Bennett (kierowca wyścigowy)|Carl Bennett]]"},
"casper stevenson": {"country": "GBR", "link": "[[Casper Stevenson]]"},
"chandler hull": {"country": "USA", "link": "[[Chandler Hull]]"},
"charles milesi": {"country": "FRA", "link": "[[Charles Milesi]]"},
"charlie eastwood": {"country": "IRL", "link": "[[Charlie Eastwood]]"},
"christian rasmussen": {"country": "DNK", "link": "[[Christian Rasmussen]]"},
"christian ried": {"country": "DEU", "link": "[[Christian Ried]]"},
"claudio schiavoni": {"country": "ITA", "link": "[[Claudio Schiavoni]]"},
"clément mateu": {"country": "FRA", "link": "[[Clément Mateu]]"},
"colin braun": {"country": "USA", "link": "[[Colin Braun]]"},
"connor bloum": {"country": "USA", "link": "[[Connor Bloum]]"},
"conrad laursen": {"country": "DNK", "link": "[[Conrad Laursen]]"},
"daniel juncadella": {"country": "ESP", "link": "[[Daniel Juncadella]]"},
"daniel mancinelli": {"country": "ITA", "link": "[[Daniel Mancinelli]]"},
"daniel schneider": {"country": "BRA", "link": "[[Daniel Schneider]]"},
"daniel serra": {"country": "BRA", "link": "[[Daniel Serra]]"},
"daniil kvyat": {"country": "", "link": "[[Daniił Kwiat]]"},
"darren leung": {"country": "GBR", "link": "[[Darren Leung]]"},
"david heinemeier-hansson": {"country": "DNK", "link": "[[David Heinemeier Hansson|David Heinemeier-Hansson]]"},
"david perel": {"country": "ZAF", "link": "[[David Perel]]"},
"david pittard": {"country": "GBR", "link": "[[David Pittard]]"},
"davide rigon": {"country": "ITA", "link": "[[Davide Rigon]]"},
"dennis andersem": {"country": "DNK", "link": "[[Dennis Andersen]]"},
"dennis andersen": {"country": "DNK", "link": "[[Dennis Andersen]]"},
"dennis olsen": {"country": "NOR", "link": "[[Dennis Olsen]]"},
"devlin defrancesco": {"country": "CAN", "link": "[[Devlin DeFrancesco]]"},
"diego alessi": {"country": "ITA", "link": "[[Diego Alessi]]"},
"doriane pin": {"country": "FRA", "link": "[[Doriane Pin]]"},
"dries vanthoor": {"country": "BEL", "link": "[[Dries Vanthoor]]"},
"duncan cameron": {"country": "GBR", "link": "[[Duncan Cameron]]"},
"dwight merriman": {"country": "USA", "link": "[[Dwight Merriman]]"},
"earl bamber": {"country": "NZL", "link": "[[Earl Bamber]]"},
"ed jones": {"country": "ARE", "link": "[[Ed Jones (kierowca)|Ed Jones]]"},
"edoardo mortara": {"country": "ITA", "link": "[[Edoardo Mortara]]"},
"efrin castro": {"country": "DOM", "link": "[[Efrin Castro]]"},
"eric lux": {"country": "USA", "link": "[[Eric Lux (kierowca wyścigowy)|Eric Lux]]"},
"eric trouillet": {"country": "FRA", "link": "[[Eric Trouillet]]"},
"erwan bastard": {"country": "FRA", "link": "[[Erwan Bastard]]"},
"esteban guerrieri": {"country": "ARG", "link": "[[Esteban Guerrieri]]"},
"esteban gutierrez": {"country": "MEX", "link": "[[Esteban Gutiérrez]]"},
"esteban masson": {"country": "FRA", "link": "[[Esteban Masson]]"},
"fabien michal": {"country": "FRA", "link": "[[Fabien Michal]]"},
"fabio scherer": {"country": "CHE", "link": "[[Fabio Scherer]]"},
"ferdinand habsburg": {"country": "AUT", "link": "[[Ferdinand Zvonimir Habsburg-Lothringen|Ferdinand Habsburg]]"},
"filip ugran": {"country": "ROU", "link": "[[Filip Ugran]]"},
"filipe albuquerque": {"country": "PRT", "link": "[[Filipe Albuquerque]]"},
"francesco castellacci": {"country": "ITA", "link": "[[Francesco Castellacci]]"},
"franck mailleux": {"country": "FRA", "link": "[[Franck Mailleux]]"},
"franck perera": {"country": "FRA", "link": "[[Franck Perera]]"},
"francois perrodo": {"country": "FRA", "link": "[[François Perrodo]]"},
"françois heriau": {"country": "FRA", "link": "[[François Heriau]]"},
"françois perrodo": {"country": "FRA", "link": "[[François Perrodo]]"},
"fred poordad": {"country": "USA", "link": "[[Fred Poordad]]"},
"frederick lubin": {"country": "GBR", "link": "[[Frederick Lubin]]"},
"frederik schandorff": {"country": "DNK", "link": "[[Frederik Schandorff]]"},
"frédéric makowiecki": {"country": "FRA", "link": "[[Frédéric Makowiecki]]"},
"gabby chaves": {"country": "COL", "link": "[[Gabriel Chaves|Gabby Chaves]]"},
"gabriel aubry": {"country": "FRA", "link": "[[Gabriel Aubry (kierowca wyścigowy)|Gabriel Aubry]]"},
"gael julien": {"country": "FRA", "link": "[[Gael Julien]]"},
"gar robinson": {"country": "USA", "link": "[[Gar Robinson]]"},
"garett grist": {"country": "CAN", "link": "[[Garett Grist]]"},
"garnet patterson": {"country": "AUS", "link": "[[Garnet Patterson]]"},
"george kurtz": {"country": "USA", "link": "[[George Kurtz]]"},
"giacomo petrobelli": {"country": "ITA", "link": "[[Giacomo Petrobelli]]"},
"giammarco levorato": {"country": "ITA", "link": "[[Giammarco Levorato]]"},
"gianmaria bruni": {"country": "ITA", "link": "[[Gianmaria Bruni]]"},
"giorgio roda": {"country": "ITA", "link": "[[Giorgio Roda]]"},
"giorgio sernagiotto": {"country": "ITA", "link": "[[Giorgio Sernagiotto]]"},
"glenn van berlo": {"country": "NLD", "link": "[[Glenn van Berlo]]"},
"gregory huffaker ii": {"country": "USA", "link": "[[Scott Huffaker|Gregory Huffaker II]]"},
"grégoire saucy": {"country": "CHE", "link": "[[Grégoire Saucy]]"},
"guilherme moura de oliveira": {"country": "PRT", "link": "[[Guilherme de Oliveira]]"},
"gunnar jeannette": {"country": "USA", "link": "[[Gunnar Jeannette]]"},
"gustav birch": {"country": "DNK", "link": "[[Gustav Birch]]"},
"gustav dahlmann birch": {"country": "DNK", "link": "[[Gustav Birch]]"},
"gustavo menezes": {"country": "USA", "link": "[[Gustavo Menezes]]"},
"guy smith": {"country": "GBR", "link": "[[Guy Smith (kierowca)|Guy Smith]]"},
"harry tincknell": {"country": "GBR", "link": "[[Harry Tincknell]]"},
"henrik hedman": {"country": "SWE", "link": "[[Henrik Hedman]]"},
"hiroshi koizumi": {"country": "JPN", "link": "[[Hiroshi Koizumi (kierowca wyścigowy)|Hiroshi Koizumi]]"},
"horst felbermayr": {"country": "AUT", "link": "[[Horst Felbermayr]]"},
"ian james": {"country": "USA", "link": "[[Ian James]]"},
"ian rodriguez": {"country": "GTM", "link": "[[Ian Rodríguez]]"},
"indy dontje": {"country": "NLD", "link": "[[Indy Dontje]]"},
"jack aitken": {"country": "GBR", "link": "[[Jack Aitken]]"},
"jack hawksworth": {"country": "GBR", "link": "[[Jack Hawksworth]]"},
"jack manchester": {"country": "GBR", "link": "[[Jack Manchester]]"},
"jacques wolff": {"country": "FRA", "link": "[[Jacques Wolff]]"},
"jakub smiechowski": {"country": "POL", "link": "[[Jakub Śmiechowski]]"},
"james allen": {"country": "AUS", "link": "[[James Allen (kierowca wyścigowy)|James Allen]]"},
"james calado": {"country": "GBR", "link": "[[James Calado]]"},
"james cottingham": {"country": "GBR", "link": "[[James Cottingham]]"},
"james dayson": {"country": "CAN", "link": "[[James Dayson]]"},
"james mcguire": {"country": "USA", "link": "[[James McGuire]]"},
"james winslow": {"country": "GBR", "link": "[[James Winslow]]"},
"jan heylen": {"country": "BEL", "link": "[[Jan Heylen]]"},
"jaxon evans": {"country": "NZL", "link": "[[Jaxon Evans]]"},
"jean-baptiste lahaye": {"country": "FRA", "link": "[[Jean-Baptiste Lahaye]]"},
"jean-eric vergne": {"country": "FRA", "link": "[[Jean-Éric Vergne]]"},
"jean-karl vernay": {"country": "FRA", "link": "[[Jean-Karl Vernay]]"},
"jean-ludovic foubert": {"country": "FRA", "link": "[[Jean-Ludovic Foubert]]"},
"jean-éric vergne": {"country": "FRA", "link": "[[Jean-Éric Vergne]]"},
"jens møller": {"country": "DNK", "link": "[[Jens Reno Møller]]"},
"jens reno møller": {"country": "DNK", "link": "[[Jens Reno Møller]]"},
"jenson button": {"country": "GBR", "link": "[[Jenson Button]]"},
"jimmie johnson": {"country": "USA", "link": "[[Jimmie Johnson]]"},
"joao barbosa": {"country": "USA", "link": "[[João Barbosa]]"},
"joao paulo de oliveira": {"country": "BRA", "link": "[[João Paulo de Oliveira (kierowca)|João Paulo de Oliveira]]"},
"job van uitert": {"country": "NLD", "link": "[[Job van Uitert]]"},
"joel sturm": {"country": "DEU", "link": "[[Joel Sturm]]"},
"john falb": {"country": "USA", "link": "[[John Falb]]"},
"john hartshorne": {"country": "GBR", "link": "[[John Hartshorne]]"},
"johnny laursen": {"country": "DNK", "link": "[[Johnny Laursen]]"},
"jon lancaster": {"country": "GBR", "link": "[[Jon Lancaster]]"},
"jonas ried": {"country": "DEU", "link": "[[Jonas Ried]]"},
"jonathan aberdein": {"country": "ZAF", "link": "[[Jonathan Aberdein]]"},
"jonathan adam": {"country": "GBR", "link": "[[Jonathan Adam]]"},
"jordan pepper": {"country": "ZAF", "link": "[[Jordan Pepper]]"},
"jordan taylor": {"country": "USA", "link": "[[Jordan Taylor]]"},
"jose maria lopez": {"country": "ARG", "link": "[[José María López]]"},
"josef newgarden": {"country": "USA", "link": "[[Josef Newgarden]]"},
"josh burdon": {"country": "AUS", "link": "[[Josh Burdon]]"},
"josh pierson": {"country": "USA", "link": "[[Joshua Pierson|Josh Pierson]]"},
"joshua caygill": {"country": "GBR", "link": "[[Joshua Caygill]]"},
"joshua pierson": {"country": "USA", "link": "[[Joshua Pierson|Josh Pierson]]"},
"juan manuel correa": {"country": "USA", "link": "[[Juan Manuel Correa]]"},
"juan pablo montoya": {"country": "COL", "link": "[[Juan Pablo Montoya]]"},
"jules gounon": {"country": "FRA", "link": "[[Jules Gounon]]"},
"julien andlauer": {"country": "FRA", "link": "[[Julien Andlauer]]"},
"julien canal": {"country": "FRA", "link": "[[Julien Canal]]"},
"julien piguet": {"country": "FRA", "link": "[[Julien Piguet]]"},
"kai askey": {"country": "GBR", "link": "[[Kai Askey]]"},
"kamui kobayashi": {"country": "JPN", "link": "[[Kamui Kobayashi]]"},
"katherine legge": {"country": "GBR", "link": "[[Katherine Legge]]"},
"kay van berlo": {"country": "NLD", "link": "[[Kay van Berlo]]"},
"kei cozzolino": {"country": "JPN", "link": "[[Kei Cozzolino]]"},
"kelvin van der linde": {"country": "ZAF", "link": "[[Kelvin van der Linde]]"},
"kenton koch": {"country": "USA", "link": "[[Kenton Koch]]"},
"kevin estre": {"country": "FRA", "link": "[[Kévin Estre]]"},
"klaus bachler": {"country": "AUT", "link": "[[Klaus Bachler]]"},
"kriton lentoudis": {"country": "GRC", "link": "[[Kriton Lentoudis]]"},
"kyffin simpson": {"country": "BRB", "link": "[[Kyffin Simpson]]"},
"kyle marcelli": {"country": "CAN", "link": "[[Kyle Marcelli]]"},
"kévin estre": {"country": "FRA", "link": "[[Kévin Estre]]"},
"lars kern": {"country": "DEU", "link": "[[Lars Kern]]"},
"laurens vanthoor": {"country": "BEL", "link": "[[Laurens Vanthoor]]"},
"laurents hörr": {"country": "DEU", "link": "[[Laurents Hörr]]"},
"leonard weiss": {"country": "DEU", "link": "[[Leonard Weiss]]"},
"lilou wadoux ducellier": {"country": "FRA", "link": "[[Lilou Wadoux|Lilou Wadoux Ducellier]]"},
"lilou wadoux": {"country": "FRA", "link": "[[Lilou Wadoux]]"},
"lorcan hanafin": {"country": "GBR", "link": "[[Lorcan Hanafin]]"},
"loris spinelli": {"country": "ITA", "link": "[[Loris Spinelli]]"},
"louis deletraz": {"country": "CHE", "link": "[[Louis Delétraz]]"},
"louis delétraz": {"country": "CHE", "link": "[[Louis Delétraz]]"},
"louis prette": {"country": "ITA", "link": "[[Louis Prette]]"},
"loïc duval": {"country": "FRA", "link": "[[Loïc Duval]]"},
"luis felipe derani": {"country": "BRA", "link": "[[Pipo Derani|Luis Felipe Derani]]"},
"luis perez companc": {"country": "ARG", "link": "[[Luís Pérez Companc]]"},
"luke berkeley": {"country": "USA", "link": "[[Luke Berkeley]]"},
"malthe jakobsen": {"country": "DNK", "link": "[[Malthe Jakobsen]]"},
"manuel espirito santo": {"country": "PRT", "link": "[[Manuel Espirito Santo]]"},
"manuel maldonado": {"country": "GBR", "link": "[[Manuel Maldonado]]"},
"marco sorensen": {"country": "DNK", "link": "[[Marco Sørensen]]"},
"marco sørensen": {"country": "DNK", "link": "[[Marco Sørensen]]"},
"marco wittmann": {"country": "DEU", "link": "[[Marco Wittmann]]"},
"marcos siebert": {"country": "ARG", "link": "[[Marcos Siebert]]"},
"marino sato": {"country": "JPN", "link": "[[Marino Satō]]"},
"martin berry": {"country": "SGP", "link": "[[Martin Berry]]"},
"martin rump": {"country": "EST", "link": "[[Martin Rump]]"},
"mateusz kaprzyk": {"country": "POL", "link": "[[Mateusz Kaprzyk]]"},
"mathias beche": {"country": "CHE", "link": "[[Mathias Beche]]"},
"mathieu jaminet": {"country": "FRA", "link": "[[Mathieu Jaminet]]"},
"matt campbell": {"country": "AUS", "link": "[[Matt Campbell]]"},
"matteo cairoli": {"country": "ITA", "link": "[[Matteo Cairoli]]"},
"matteo cressoni": {"country": "ITA", "link": "[[Matteo Cressoni]]"},
"matthew bell": {"country": "GBR", "link": "Matthew Bell"},
"matthew griffin": {"country": "IRL", "link": "[[Matt Griffin|Matthew Griffin]]"},
"matthew richard bell": {"country": "GBR", "link": "Matthew Richard Bell"},
"matthias kaiser": {"country": "LIE", "link": "[[Matthias Kaiser]]"},
"matthias luethen": {"country": "DEU", "link": "[[Matthias Lüthen]]"},
"matthieu lahaye": {"country": "FRA", "link": "[[Matthieu Lahaye]]"},
"matthieu vaxiviere": {"country": "FRA", "link": "[[Matthieu Vaxivière]]"},
"maxime martin": {"country": "BEL", "link": "[[Maxime Martin]]"},
"maxime robin": {"country": "FRA", "link": "[[Maxime Robin]]"},
"maxwell root": {"country": "USA", "link": "[[Maxwell Root]]"},
"memo rojas": {"country": "MEX", "link": "[[Memo Rojas]]"},
"michael christensen": {"country": "DNK", "link": "[[Michael Christensen]]"},
"michael dinan": {"country": "USA", "link": "[[Michael Dinan]]"},
"michael fassbender": {"country": "IRL", "link": "[[Michael Fassbender]]"},
"michael jensen": {"country": "DNK", "link": "[[Michael Jensen (kierowca wyścigowy)|Michael Jensen]]"},
"michael wainwright": {"country": "GBR", "link": "[[Michael Wainwright]]"},
"michelle gatting": {"country": "DNK", "link": "[[Michelle Gatting]]"},
"mick schumacher": {"country": "DEU", "link": "[[Mick Schumacher]]"},
"miguel cristóvão": {"country": "PRT", "link": "[[Miguel Cristóvão]]"},
"miguel molina": {"country": "ESP", "link": "[[Miguel Molina (kierowca wyścigowy)|Miguel Molina]]"},
"miguel pedro ramos": {"country": "PRT", "link": "[[Miguel Ramos]]"},
"mike conway": {"country": "GBR", "link": "[[Mike Conway]]"},
"mike rockenfeller": {"country": "DEU", "link": "[[Mike Rockenfeller]]"},
"mikkel jensen": {"country": "DNK", "link": "[[Mikkel Jensen]]"},
"mikkel mac": {"country": "DNK", "link": "[[Mikkel Mac]]"},
"mikkel pedersen": {"country": "DNK", "link": "[[Mikkel Pedersen]]"},
"mirko bortolotti": {"country": "ITA", "link": "[[Mirko Bortolotti]]"},
"morris schuring": {"country": "NLD", "link": "[[Morris Schuring]]"},
"naoki yokomizo": {"country": "JPN", "link": "[[Naoki Yokomizo]]"},
"nathanael berthon": {"country": "FRA", "link": "[[Nathanaël Berthon]]"},
"nathanaël berthon": {"country": "FRA", "link": "[[Nathanaël Berthon]]"},
"neel jani": {"country": "CHE", "link": "[[Neel Jani]]"},
"nelson piquet jr": {"country": "BRA", "link": "[[Nelson Piquet Jr.]]"},
"nicholas tandy": {"country": "GBR", "link": "[[Nick Tandy]]"},
"nick adcock": {"country": "GBR", "link": "[[Nick Adcock]]"},
"nick moss": {"country": "GBR", "link": "[[Nick Moss]]"},
"nick tandy": {"country": "GBR", "link": "[[Nick Tandy]]"},
"nick yelloly": {"country": "GBR", "link": "[[Nick Yelloly]]"},
"nicki thiim": {"country": "DNK", "link": "[[Nicki Thiim]]"},
"nicklas nielsen": {"country": "DNK", "link": "[[Nicklas Nielsen]]"},
"nicky catsburg": {"country": "NLD", "link": "[[Nick Catsburg|Nicky Catsburg]]"},
"nico müller": {"country": "CHE", "link": "[[Nico Müller]]"},
"nico pino": {"country": "CHL", "link": "[[Nicolás Pino (kierowca wyścigowy)|Nico Pino]]"},
"nico varrone": {"country": "ARG", "link": "[[Nicolás Varrone]]"},
"nicolas costa": {"country": "BRA", "link": "[[Nicolas Costa]]"},
"nicolas lapierre": {"country": "FRA", "link": "[[Nicolas Lapierre]]"},
"nicolas pino": {"country": "CHL", "link": "[[Nicolás Pino (kierowca wyścigowy)|Nicolas Pino]]"},
"nicolas varrone": {"country": "ARG", "link": "[[Nicolás Varrone]]"},
"nolan siegel": {"country": "USA", "link": "[[Nolan Siegel]]"},
"norman nato": {"country": "FRA", "link": "[[Norman Nato]]"},
"nyck de vries": {"country": "NLD", "link": "[[Nyck de Vries]]"},
"oliver jarvis": {"country": "GBR", "link": "[[Oliver Jarvis]]"},
"oliver rasmussen": {"country": "DNK", "link": "[[Oliver Rasmussen]]"},
"olli caldwell": {"country": "GBR", "link": "[[Olli Caldwell]]"},
"ollie millroy": {"country": "GBR", "link": "[[Ollie Millroy]]"},
"oscar tunjo": {"country": "COL", "link": "[[Oscar Andrés Tunjo|Oscar Tunjo]]"},
"patrick pilet": {"country": "FRA", "link": "[[Patrick Pilet]]"},
"paul dalla lana": {"country": "CAN", "link": "[[Paul Dalla Lana]]"},
"paul di resta": {"country": "GBR", "link": "[[Paul di Resta]]"},
"paul lafargue": {"country": "FRA", "link": "[[Paul Lafargue (kierowca wyścigowy)|Paul Lafargue]]"},
"paul loup chatin": {"country": "FRA", "link": "[[Paul-Loup Chatin]]"},
"paul-loup chatin": {"country": "FRA", "link": "[[Paul-Loup Chatin]]"},
"pedro perino": {"country": "PRT", "link": "[[Pedro Perino]]"},
"philip hanson": {"country": "GBR", "link": "[[Philip Hanson]]"},
"philipp eng": {"country": "AUT", "link": "[[Philipp Eng]]"},
"pietro fittipaldi": {"country": "BRA", "link": "[[Pietro Fittipaldi]]"},
"pipo derani": {"country": "BRA", "link": "[[Pipo Derani]]"},
"pj hyett": {"country": "USA", "link": "[[P.J. Hyett]]"},
"raffaele marciello": {"country": "CHE", "link": "[[Raffaele Marciello]]"},
"rahel frey": {"country": "CHE", "link": "[[Rahel Frey]]"},
"rasmus lindh": {"country": "SWE", "link": "[[Rasmus Lindh]]"},
"renger van der zande": {"country": "NLD", "link": "[[Renger van der Zande]]"},
"rené binder": {"country": "AUT", "link": "[[René Binder]]"},
"rené rast": {"country": "DEU", "link": "[[René Rast]]"},
"reshad de gerus": {"country": "FRA", "link": "[[Reshad de Gerus]]"},
"reshad de gérus": {"country": "FRA", "link": "[[Reshad de Gerus]]"},
"riccardo pera": {"country": "ITA", "link": "[[Riccardo Pera]]"},
"richard lietz": {"country": "AUT", "link": "[[Richard Lietz]]"},
"richard westbrook": {"country": "GBR", "link": "[[Richard Westbrook]]"},
"ricky taylor": {"country": "USA", "link": "[[Ricky Taylor]]"},
"robby foley": {"country": "USA", "link": "[[Robby Foley]]"},
"robert kubica": {"country": "POL", "link": "[[Robert Kubica]]"},
"robert shwartzman": {"country": "ISR", "link": "[[Robert Szwarcman]]"},
"robin frijns": {"country": "NLD", "link": "[[Robin Frijns]]"},
"rodrigo sales": {"country": "USA", "link": "[[Rodrigo Sales]]"},
"romain dumas": {"country": "FRA", "link": "[[Romain Dumas]]"},
"ross gunn": {"country": "GBR", "link": "[[Ross Gunn]]"},
"rui aguas": {"country": "PRT", "link": "[[Rui Águas (kierowca wyścigowy)|Rui Águas]]"},
"rui andrade": {"country": "AGO", "link": "[[Rui Pinto de Andrade|Rui Andrade]]"},
"ryan cullen": {"country": "GBR", "link": "[[Ryan Cullen]]"},
"ryan dalziel": {"country": "GBR", "link": "[[Ryan Dalziel]]"},
"ryan hardwick": {"country": "USA", "link": "[[Ryan Hardwick]]"},
"ryan harper-ellam": {"country": "GBR", "link": "[[Ryan Harper-Ellam]]"},
"ryo hirakawa": {"country": "JPN", "link": "[[Ryō Hirakawa]]"},
"salih yoluc": {"country": "TUR", "link": "[[Salih Yoluç]]"},
"sarah bovy": {"country": "BEL", "link": "[[Sarah Bovy]]"},
"satoshi hoshino": {"country": "JPN", "link": "[[Satoshi Hoshino]]"},
"scott dixon": {"country": "NZL", "link": "[[Scott Dixon]]"},
"scott huffaker": {"country": "USA", "link": "[[Scott Huffaker]]"},
"scott mclaughlin": {"country": "NZL", "link": "[[Scott McLaughlin]]"},
"sean gelael": {"country": "IDN", "link": "[[Sean Gelael]]"},
"seb priaulx": {"country": "GBR", "link": "[[Sebastian Priaulx|Seb Priaulx]]"},
"sebastian alvarez": {"country": "GBR", "link": "[[Sebastián Álvarez]]"},
"sebastian montoya": {"country": "COL", "link": "[[Sebastián Montoya]]"},
"sebastien bourdais": {"country": "FRA", "link": "[[Sébastien Bourdais]]"},
"sheldon van der linde" : {"country": "ZAF", "link": "[[Sheldon van der Linde]]"},
"simon mann": {"country": "USA", "link": "[[Simon Mann (kierowca wyścigowy)|Simon Mann]]"},
"simon pagenaud": {"country": "FRA", "link": "[[Simon Pagenaud]]"},
"spencer pumpelly": {"country": "USA", "link": "[[Spencer Pumpelly]]"},
"stevan mcaleer": {"country": "GBR", "link": "[[Stevan McAleer]]"},
"steven thomas": {"country": "USA", "link": "[[Steven Thomas]]"},
"stoffel vandoorne": {"country": "BEL", "link": "[[Stoffel Vandoorne]]"},
"sébastien baud": {"country": "FRA", "link": "[[Sébastien Baud (kierowca wyścigowy)|Sébastien Baud]]"},
"sébastien bourdais": {"country": "FRA", "link": "[[Sébastien Bourdais]]"},
"sébastien buemi": {"country": "CHE", "link": "[[Sébastien Buemi]]"},
"takeshi kimura": {"country": "JPN", "link": "[[Takeshi Kimura]]"},
"tatiana calderon": {"country": "COL", "link": "[[Tatiana Calderón]]"},
"thomas flohr": {"country": "CHE", "link": "[[Thomas Flohr]]"},
"thomas merrill": {"country": "USA", "link" : "[[Thomas Merrill]]"},
"thomas neubauer": {"country": "FRA", "link": "[[Thomas Neubauer]]"},
"tijmen van der helm": {"country": "NLD", "link": "[[Tijmen van der Helm]]"},
"till bechtolsheimer": {"country": "GBR", "link": "[[Till Bechtolsheimer]]"},
"timur boguslavskiy": {"country": "_", "link": "[[Timur Bogusławskij]]"},
"tom blomqvist": {"country": "GBR", "link": "[[Tom Blomqvist]]"},
"tom dillmann": {"country": "FRA", "link": "[[Tom Dillmann]]"},
"tom gamble": {"country": "GBR", "link": "[[Tom Gamble]]"},
"tom van rompuy": {"country": "BEL", "link": "[[Tom van Rompuy]]"},
"tomonobu fujii": {"country": "JPN", "link": "[[Tomonobu Fujii]]"},
"tonis kasemets": {"country": "USA", "link": "[[Tonis Kasemets]]"},
"torsten kratz": {"country": "DEU", "link": "[[Torsten Kratz]]"},
"tristan vautier": {"country": "FRA", "link": "[[Tristan Vautier]]"},
"ugo de wilde": {"country": "BEL", "link": "[[Ugo de Wilde]]"},
"ulysse de pauw": {"country": "BEL", "link": "[[Ulysse de Pauw]]"},
"valdemar eriksen": {"country": "DNK", "link": "[[Valdemar Eriksen]]"},
"valentin hasse-clot": {"country": "FRA", "link": "[[Valentin Hasse-Clot]]"},
"valentino rossi": {"country": "ITA", "link": "[[Valentino Rossi]]"},
"vladislav lomko": {"country": "_", "link": "[[Władisław Łomko]]"},
"wayne boyd": {"country": "GBR", "link": "[[Wayne Boyd]]"},
"will stevens": {"country": "GBR", "link": "[[Will Stevens]]"},
"william stevens": {"country": "GBR", "link": "[[Will Stevens|William Stevens]]"},
"wyatt brichacek": {"country": "USA", "link": "[[Wyatt Brichacek]]"},
"yasser shahin": {"country": "AUS", "link": "[[Yasser Shahin]]"},
"yifei ye": {"country": "CHN", "link": "[[Ye Yifei|Yifei Ye]]"},
"yorikatsu tsujiko": {"country": "JPN", "link": "[[Yorikatsu Tsujiko]]"},
"zacharie robichon": {"country": "CAN", "link": "[[Zacharie Robichon]]"},
}

# Dane o zespołach
teams = {
"#10 Eurointernational": {"country": "ITA", "link": "#10 [[EuroInternational|Eurointernational]]"},
"#10 Vector Sport": {"country": "GBR", "link": "#10 [[Vector Sport]]"},
"#11 Eurointernational": {"country": "ITA", "link": "#11 [[EuroInternational|Eurointernational]]"},
"#11 Isotta Fraschini": {"country": "ITA", "link": "#11 [[Duqueine Team|Isotta Fraschini]]"},
"#11 TDS Racing": {"country": "FRA", "link": "#11 [[TDS Racing]]"},
"#12 Hertz Team JOTA": {"country": "GBR", "link": "#12 [[The Hertz Corporation|Hertz]] [[Jota Sport|Team JOTA]]"},
"#12 Vasser Sullivan": {"country": "USA", "link": "#12 [[SH Racing|Vasser Sullivan]]"},
"#12 WTM by Rinaldi Racing": {"country": "DEU", "link": "#12 WTM by [[Rinaldi Racing]]"},
"#12 WTM Racing by Rinaldi": {"country": "DEU", "link": "#12 WTM by [[Rinaldi Racing]]"},
"#13 Inter Europol Competition": {"country": "POL", "link": "#13 [[Inter Europol Competition]]"},
"#14 Nielsen Racing": {"country": "GBR", "link": "#14 [[Nielsen Racing]]"},
"#15 BMW M Team WRT": {"country": "BEL", "link": "#15 [[BMW#BMW M GmbH|BMW M]] [[W Racing Team|Team WRT]]"},
"#15 RLR M Sport": {"country": "GBR", "link": "#15 [[RLR MSport]]"},
"#15 RLR MSport": {"country": "GBR", "link": "#15 [[RLR MSport]]"},
"#16 Proton Competition": {"country": "DEU", "link": "#16 [[Proton Competition]]"},
"#17 COOL Racing": {"country": "CHE", "link": "#17 [[Cool Racing|COOL Racing]]"},
"#19 Team Virage": {"country": "POL", "link": "#19 [[Team Virage]]"},
"#2 Cadillac Racing": {"country": "USA", "link": "#2 [[Chip Ganassi Racing|Cadillac Racing]]"},
"#20 Algarve Pro Racing": {"country": "PRT", "link": "#20 [[Algarve Pro Racing]]"},
"#20 BMW M Team WRT": {"country": "BEL", "link": "#20 [[BMW#BMW M GmbH|BMW M]] [[W Racing Team|Team WRT]]"},
"#20 High Class Racing": {"country": "DNK", "link": "#20 [[High Class Racing]]"},
"#21 United Autosports USA": {"country": "USA", "link": "#21 [[United Autosports|United Autosports USA]]"},
"#22 United Autosports USA": {"country": "USA", "link": "#22 [[United Autosports|United Autosports USA]]"},
"#22 United Autosports": {"country": "GBR", "link": "#22 [[United Autosports]]"},
"#23 United Autosports USA": {"country": "USA", "link": "#23 [[United Autosports|United Autosports USA]]"},
"#23 United Autosports": {"country": "GBR", "link": "#23 [[United Autosports]]"},
"#24 Nielsen Racing": {"country": "GBR", "link": "#24 [[Nielsen Racing]]"},
"#25 Algarve Pro Racing": {"country": "PRT", "link": "#25 [[Algarve Pro Racing]]"},
"#27 Heart of Racing Team": {"country": "USA", "link": "#27 [[Heart of Racing|Heart of Racing Team]]"},
"#28 IDEC Sport": {"country": "FRA", "link": "#28 [[IDEC Sport Racing|IDEC Sport]]"},
"#3 Cadillac Racing": {"country": "USA", "link": "#3 [[Chip Ganassi Racing|Cadillac Racing]]"},
"#3 DKR Engineering": {"country": "LUX", "link": "#3 [[DKR Engineering]]"},
"#30 Duqueine Team": {"country": "FRA", "link": "#30 [[Duqueine Team]]"},
"#31 Racing Spirit of Leman": {"country": "CHE", "link": "#31 [[Racing Spirit of Léman]]"},
"#31 Team WRT": {"country": "BEL", "link": "#31 [[W Racing Team|Team WRT]]"},
"#32 Inter Europol Competition": {"country": "POL", "link": "#32 [[Inter Europol Competition]]"},
"#34 Inter Europol Competition": {"country": "POL", "link": "#34 [[Inter Europol Competition]]"},
"#35 Alpine Endurance Team": {"country": "FRA", "link": "#35 [[Signature Team|Alpine Endurance Team]]"},
"#35 TDS Racing": {"country": "FRA", "link": "#35 [[TDS Racing]]"},
"#35 Ultimate": {"country": "FRA", "link": "#35 [[Graff Racing|Ultimate]]"},
"#36 Alpine Endurance Team": {"country": "FRA", "link": "#36 [[Signature Team|Alpine Endurance Team]]"},
"#37 COOL Racing": {"country": "CHE", "link": "#37 [[Cool Racing|COOL Racing]]"},
"#38 Hertz Team JOTA": {"country": "GBR", "link": "#38 [[The Hertz Corporation|Hertz]] [[Jota Sport|Team JOTA]]"},
"#39 Graff Racing": {"country": "FRA", "link": "#39 [[Graff Racing]]"},
"#4 DKR Engineering": {"country": "LUX", "link": "#4 [[DKR Engineering]]"},
"#43 DKR Engineering": {"country": "LUX", "link": "#43 [[DKR Engineering]]"},
"#43 Inter Europol Competition": {"country": "POL", "link": "#43 [[Inter Europol Competition]]"},
"#45 Algarve Pro Racing": {"country": "PRT", "link": "#45 [[Algarve Pro Racing]]"},
"#46 Team WRT": {"country": "BEL", "link": "#46 [[W Racing Team|Team WRT]]"},
"#47 COOL Racing": {"country": "CHE", "link": "#47 [[Cool Racing|COOL Racing]]"},
"#48 IDEC Sport": {"country": "FRA", "link": "#48 [[IDEC Sport Racing|IDEC Sport]]"},
"#5 Porsche Penske Motorsport": {"country": "DEU", "link": "#5 [[Porsche]] [[Penske Racing|Penske Motorsport]]"},
"#5 RLR M Sport": {"country": "GBR", "link": "#5 [[RLR MSport]]"},
"#5 RLR MSport": {"country": "GBR", "link": "#5 [[RLR MSport]]"},
"#50 Ferrari AF Corse": {"country": "ITA", "link": "#50 [[Ferrari]] [[AF Corse]]"},
"#50 Formula Racing": {"country": "DNK", "link": "#50 [[Formula Racing]]"},
"#51 AF Corse": {"country": "ITA", "link": "#51 [[AF Corse]]"},
"#51 Ferrari AF Corse": {"country": "ITA", "link": "#51 [[Ferrari]] [[AF Corse]]"},
"#51 Rick Ware Racing": {"country": "USA", "link": "#51 [[Rick Ware Racing]]"},
"#52 PR1 Mathiasen Motorsports": {"country": "USA", "link": "#52 [[PR1/Mathiasen Motorsports|PR1 Mathiasen Motorsports]]"},
"#54 AF Corse": {"country": "ITA", "link": "#54 [[AF Corse]]"},
"#54 MLT Motorsports": {"country": "USA", "link": "#54 [[MLT Motorsports]]"},
"#54 Vista AF Corse": {"country": "ITA", "link": "#54 Vista [[AF Corse]]"},
"#55 Spirit of Race": {"country": "CHE", "link": "#55 [[AF Corse|Spirit of Race]]"},
"#55 Vista AF Corse": {"country": "ITA", "link": "#55 Vista [[AF Corse]]"},
"#57 Kessel Racing": {"country": "CHE", "link": "#57 [[Kessel Racing]]"},
"#59 United Autosports": {"country": "GBR", "link": "#59 [[United Autosports]]"},
"#6 Porsche Penske Motorsport": {"country": "DEU", "link": "#6 [[Porsche]] [[Penske Racing|Penske Motorsport]]"},
"#6 Porsche Penske Motorsports": {"country": "USA", "link": "#6 [[Porsche]] [[Penske Racing|Penske Motorsports]]"},
"#60 Iron Lynx": {"country": "ITA", "link": "#60 [[Iron Lynx]]"},
"#63 Iron Lynx": {"country": "ITA", "link": "#63 [[Iron Lynx]]"},
"#63 Lamborghini Iron Lynx": {"country": "ITA", "link": "#63 [[Lamborghini]] [[Iron Lynx]]"},
"#65 Panis Racing": {"country": "FRA", "link": "#65 [[Panis Racing]]"},
"#66 JMW Motorsport": {"country": "GBR", "link": "#66 [[JMW Motorsport]]"},
"#7 Nielsen Racing": {"country": "GBR", "link": "#7 [[Nielsen Racing]]"},
"#7 Porsche Penske Motorsports": {"country": "USA", "link": "#7 [[Porsche]] [[Penske Racing|Penske Motorsports]]"},
"#7 Toyota Gazoo Racing": {"country": "JPN", "link": "#7 [[Toyota Gazoo Racing Europe|Toyota Gazoo Racing]]"},
"#70 Inception Racing": {"country": "GBR", "link": "#70 [[Inception Racing]]"},
"#72 TF Sport": {"country": "GBR", "link": "#72 [[TF Sport]]"},
"#74 Kessel Racing": {"country": "CHE", "link": "#74 [[Kessel Racing]]"},
"#74 Riley": {"country": "USA", "link": "#74 [[Riley Technologies|Riley]]"},
"#75 Porsche Penske Motorsport": {"country": "DEU", "link": "#75 [[Porsche]] [[Penske Racing|Penske Motorsport]]"},
"#77 Proton Competition": {"country": "DEU", "link": "#77 [[Proton Competition]]"},
"#777 D'Station Racing": {"country": "JPN", "link": "#777 [[D'Station Racing]]"},
"#78 Akkodis ASP Team": {"country": "FRA", "link": "#78 [[Auto Sport Promotion|Akkodis ASP Team]]"},
"#8 Team Virage": {"country": "POL", "link": "#8 [[Team Virage]]"},
"#8 Toyota Gazoo Racing": {"country": "JPN", "link": "#8 [[Toyota Gazoo Racing Europe|Toyota Gazoo Racing]]"},
"#80 AF Corse": {"country": "ITA", "link": "#80 [[AF Corse]]"},
"#81 TF Sport": {"country": "GBR", "link": "#81 [[TF Sport]]"},
"#82 TF Sport": {"country": "GBR", "link": "#82 [[TF Sport]]"},
"#83 AF Corse": {"country": "ITA", "link": "#83 [[AF Corse]]"},
"#83 Iron Dames": {"country": "ITA", "link": "#83 [[Iron Lynx|Iron Dames]]"},
"#85 Iron Dames": {"country": "ITA", "link": "#85 [[Iron Lynx|Iron Dames]]"},
"#86 GR Racing": {"country": "GBR", "link": "#86 GR Racing"},
"#87 Akkodis ASP Team": {"country": "FRA", "link": "#87 [[Auto Sport Promotion|Akkodis ASP Team]]"},
"#88 AF Corse": {"country": "ITA", "link": "#88 [[AF Corse]]"},
"#88 Proton Competition": {"country": "DEU", "link": "#88 [[Proton Competition]]"},
"#91 Manthey EMA": {"country": "DEU", "link": "#91 [[Manthey Racing|Manthey EMA]]"},
"#911 Proton Competition": {"country": "DEU", "link": "#911 [[Proton Competition]]"},
"#92 Manthey PureRxcing": {"country": "LTU", "link": "#92 [[Manthey Racing|Manthey]] [[PureRxcing]]"},
"#93 Peugeot TotalEnergies": {"country": "FRA", "link": "#93 [[Peugeot Sport|Peugeot TotalEnergies]]"},
"#93 Proton Competition": {"country": "DEU", "link": "#93 [[Proton Competition]]"},
"#94 Peugeot TotalEnergies": {"country": "FRA", "link": "#94 [[Peugeot Sport|Peugeot TotalEnergies]]"},
"#95 TF Sport": {"country": "GBR", "link": "#95 [[TF Sport]]"},
"#95 United Autosports": {"country": "GBR", "link": "#95 [[United Autosports]]"},
"#99 Proton Competition": {"country": "DEU", "link": "#99 [[Proton Competition]]"},
}

# Linki do artykułów o samochodach
cars = {
"Acura ARX-06": "[[Acura ARX-06]]",
"Acura NSX GT3": "[[Acura NSX GT3|Acura NSX GT3 Evo 22]]",
"Alpine A424": "[[Alpine A424]]",
"Aston Martin Vantage AMR LMGT3": "[[Aston Martin Vantage GT3|Aston Martin Vantage AMR LMGT3]]",
"Aston Martin Vantage AMR": "[[Aston Martin Vantage GTE (2018)|Aston Martin Vantage AMR]]",
"Aston Martin Vantage GT3": "[[Aston Martin Vantage GT3|Aston Martin Vantage GT3]]",
"BMW M Hybrid V8": "[[BMW M Hybrid V8]]",
"BMW M HYBRID V8": "[[BMW M Hybrid V8]]",
"BMW M4 GT3": "[[BMW M4 GT3]]",
"BMW M4 LMGT3": "[[BMW M4 GT3|BMW M4 LMGT3]]",
"Cadillac V-Series.R": "[[Cadillac V-Series.R]]",
"Chevrolet Corvette C8.R GTD": "[[Chevrolet Corvette C8.R|Chevrolet Corvette C8.R GTD]]",
"Chevrolet Corvette C8.R": "[[Chevrolet Corvette C8.R]]",
"Corvette Z06 LMGT3.R": "[[Chevrolet Corvette Z06 GT3.R|Corvette Z06 LMGT3.R]]",
"Duqueine D08": "[[Duqueine D-08|Duqueine M30 - D08]]",
"Duqueine M30 - D08 - Nissan": "[[Duqueine D-08|Duqueine M30 – D08]]",
"Ferrari 296 GT3": "[[Ferrari 296 GT3]]",
"Ferrari 296 LMGT3": "[[Ferrari 296 GT3|Ferrari 296 LMGT3]]",
"Ferrari 499P": "[[Ferrari 499P]]",
"Ford Mustang LMGT3": "[[Ford Mustang GT3|Ford Mustang LMGT3]]",
"Glickenhaus 007": "[[Glickenhaus 007 LMH]]",
"Isotta Fraschini Tipo6-C": "[[Isotta Fraschini Tipo 6-C]]",
"Lamborghini Huracan GT3 EVO2": "[[Lamborghini Huracán GT3 (2019)|Lamborghini Huracán GT3 Evo 2]]",
"Lamborghini Huracan LMGT3 Evo2": "[[Lamborghini Huracán GT3 (2019)|Lamborghini Huracán LMGT3 Evo2]]",
"Lamborghini SC63": "[[Lamborghini SC63]]",
"Lexus RC F GT3": "[[Lexus RC F GT3]]",
"Lexus RC F LMGT3": "[[Lexus RC F GT3|Lexus RC F LMGT3]]",
"Ligier JS P320 - Nissan": "[[Ligier JS P320]]",
"Ligier JS P320": "[[Ligier JS P320]]",
"McLaren 720S GT3 EVO": "[[McLaren 720S GT3|McLaren 720S GT3 EVO]]",
"McLaren 720S LMGT3 Evo": "[[McLaren 720S GT3|McLaren 720S LMGT3 Evo]]",
"Mercedes-AMG GT3": "[[Mercedes-AMG GT3|Mercedes-AMG GT3 Evo]]",
"Oreca 07 - Gibson": "[[Oreca 07]]",
"ORECA LMP2 07": "[[Oreca 07]]",
"Peugeot 9X8": "[[Peugeot 9X8]]",
"Porsche 911 GT3 R (992)": "[[Porsche 911 GT3 R (992)]]",
"Porsche 911 GT3 R LMGT3": "[[Porsche 911 GT3 R (992)|Porsche 911 GT3 R LMGT3 (992)]]",
"Porsche 911 RSR - 19": "[[Porsche 911 RSR-19]]",
"Porsche 963": "[[Porsche 963]]",
"Toyota GR010 - Hybrid": "[[Toyota GR010 Hybrid]]",
"Toyota GR010 HYBRID": "[[Toyota GR010 Hybrid]]",
"Vanwall Vandervell 680": "[[Vanwall Vandervell 680]]",
}